### ISSUE TITLE
Physical_oM: Creation of a BulkMaterial object 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#1017]
#### Description:

As discussed with @michaelhoehn and @ajensen19 - the concept of a bulk material object is useful in the context of the https://github.com/BHoM/LifeCycleAssessment_Toolkit 

This object will be defined by something like

``` C# 
public class BulkMaterial : BHoMObject, IElementM
{
    public virtual List<BH.oM.Geometry.ISolid> Geometry { get; set; }
    public virtual MaterialComposition MaterialComposition { get; set; }

}

```

**Comment by al-fisher** [comment]
Opportunity here while we do it to also create a new interface `BH.oM.Physical.Elements.ISolid` which can impose the above properties - and may actually be helpful for other more sculptural entities in the future and concepts like Furniture or free form objects like concrete  or connections, CNC parts etc. etc.  

``` C#
interface BH.oM.Physical.Elements.ISolid : IBHoMObject, IPhysical, IElement3D, IElementM
```

Which brings us to IElement3D again @IsakNaslundBh @pawelbaran 😄 
Might be time to add as shell interface (pun intended 😆) to start building out going forward. Very limited functionality, as discussed previously, in first instance

**Comment by pawelbaran** [comment]
Hmm I am wondering how does that fit into the discussion started in https://github.com/BHoM/Revit_Toolkit/pull/774? In general, the problem there is that currently `MaterialComposition` consists of a collection of `Materials` and a collection of `doubles` that sum to 1.0, which requires:
1. wrapping the disjointed pairs `<Material, Volume as double>` together into a single `MaterialComposition` on pull
2. unwrapping into the pairs above on postproc

As long as it may make sense on the code level, the UX of it is not great, to say the least (the user gets a total volume and the `MaterialComposition` and needs to do the math him/herself to learn how much of each material is in the element). I thought the solution for that could be adding a `double TotalVolume` property to the `MaterialComposition` object and a couple of `Query` methods to extract the volumes per material.

In practice, the above solution would be quite similar to `BulkMaterial`, with the only difference being to store the volume as a number, not geometry. Of course having the geometry instead of the number sounds great, but e.g. in case of Revit we are not able to extract solids yet, while we are able to extract the volumes as numbers. Therefore, a concept between `BulkMaterial` and `MaterialComposition` would be more than welcome.

Does that make sense @al-fisher? I am looping @enarhi in as the originator of the Revit issue.

**Comment by al-fisher** [comment]
@michaelhoehn - assigning this following our chat. Think this is ready to be tackled in up coming sprints now.
Looking at @pawelbaran's comment above also - can cover in discussion in our next meeting - cheers
