### ISSUE TITLE
Geometry_oM: Vector extension functions

### ISSUE THREAD

**Issue by LightosTomJ** [BHoM/BHoM#1090]
To prove and implement 4D & 5D functionality, I need some additional functions, as class extensions for vector objects. These include but are not limited to:

- Unit vector
- Dot product
- Cross Product
- IsAlmostEqualTo (I've seen your '==' operator, but floating point errors can fail this test sometimes)

Please can you advise:
1. How you want the extension methods to be structured in the solution/project?
2. Are unit tests required for this option? If so, where are the unit test projects?

**Comment by al-fisher** [comment]
Hi @LightosTomJ 

These specific methods are provided across in the [Geometry_Engine](https://github.com/BHoM/BHoM_Engine/tree/master/Geometry_Engine) project as part of the [BHoM_Engine](https://github.com/BHoM/BHoM_Engine/blob/master/README.md) repo.

The structure of the BHoM is such that all of the methods operating on objects are defined in separate Engines - largely as extension methods. For some of our primitives like the Vector - we do, as you have seen, have a few operator overloads expressed directly in the class definition file as required by C#. But this is the exception rather than the rule.

You should therefore find (I hope) much of the functionality you need in the Engines. Do take a look at the methods listed below. 

Let us know how you get on - and certainly if there are any other methods or functionality you would want to add, we can certainly help.

---

UnitVector:

``` C# 
BH.Engine.Geometry.Modify.Normalise(this Vector vector) 
```
https://github.com/BHoM/BHoM_Engine/blob/master/Geometry_Engine/Modify/Normalise.cs

---

Dot & Cross Products

``` C# 
BH.Engine.Geometry.Query.DotProduct(this Vector a, Vector b)
BH.Engine.Geometry.Query.CrossProduct(this Vector a, Vector b)
```
https://github.com/BHoM/BHoM_Engine/blob/master/Geometry_Engine/Query/Product.cs

---

IsAlmostEqualTo:

``` C# 
BH.Engine.Geometry.Query.IsEqual(this Vector vector, Vector other, double tolerance = Tolerance.Distance)
```
https://github.com/BHoM/BHoM_Engine/blob/master/Geometry_Engine/Query/IsEqual.cs

**Comment by LightosTomJ** [comment]
I underestimated the quantity of methods you've already covered, very impressive. I also like the spelling of 'normalise'!! I'll test the behaviour of geometry in my test project.

I have deleted this branch.

**Comment by al-fisher** [comment]
Brilliant - let us know how you get on
