### ISSUE TITLE
Physical_oM: Creation of more foundations objects

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/BHoM#1155]
#### Description:

Creation of Footing, PileCap and GradeBeam or similarly named Foundations elements. 

These types of objects make up a very large percentage of LCA-related impacts and would be very helpful if integrated in our typical workflows as a simple use case. 

Has any previous thought gone into the creation of these objects for integration in other workflows? 
@IsakNaslundBh @pawelbaran 

FYI: @mchaf

**Comment by pawelbaran** [comment]
Yeah we had a discussion about that a few times already (I bet you can find some existing issues), each time the idea has been dropped due to lack of in-depth understanding of geo engineering combined with time constraints. However, it is definitely worth adding the objects to the oM! The question would be, should we start from `Physical`, `Structural` or both in parallel?

Looping @rwemay in

**Comment by al-fisher** [comment]
Yes @mchaf agreed with implementing in Physical! This aligns with most recent conversations with @IsakNaslundBh I believe! 
Also agree, will be great to get this implemented! 😁 
👍

**Comment by michaelhoehn** [comment]
Happy to leave this issue open as part of our annual clean-up efforts. Would be great to get this planned with structures and foundational @IsakNaslundBh
