### ISSUE TITLE
Issue with BHoM Nuget

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM#1238]
#### Description:

I connected today BHoM via Nuget **4.1.0-beta** and our code returns this error

_System.IO.FileNotFoundException: 'Could not load file or assembly 'DeepCloner, Version=0.10.0.0, Culture=neutral, PublicKeyToken=dc0b95cf99bf4e99' or one of its dependencies. The system cannot find the file specified.'_

we did some research  and noticed that DeepCloner was missing from BHoM
at the end we had to add also BHoM.Engine 3.3.0-alpha and it works.... 
however you must have these two loaded...

#### Steps to reproduce:

![image](https://user-images.githubusercontent.com/26113670/117305433-a7d41480-ae76-11eb-80c6-4590ebda7680.png)

**Comment by FraserGreenroyd** [comment]
@michaldengusiak the nugets have just been updated to the 4.2.0-beta versions today.

The `DeepCloner` is a dependency from `BHoM_Engine` nuget rather than `BHoM` (`BHoM` itself as the oMs do not depend on `DeepCloner`), so I recommend adding both nugets to get the full functionality of oM and Engine methods.

Can you try that and update the issue if you're still getting trouble?

**Comment by FraserGreenroyd** [comment]
Closing issue as nothing more reported to investigate.
