### ISSUE TITLE
Structure_oM: Rebar intent and Reinforcement Bar objects

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM#1241]
#### Description:

Two levels here, I think the `RebarIntent` and `Rebar` objects should be linked by a common interface because they share similarities. 

1. Rebar Intent
- Inputs by users as a `List<Points>` and `List<ICurve>` and this allows flexibility in terms of multiple layers of longitudinal bars, and links etc. and maintains the existing `Longitudinal` and `Transverse` reinforcement (may require some changes to removing layouts)
- Allows the user to sketch the rebar intent and assign that to object
- If they want to use the `SectionProperty` from the `Bar` or `IAreaElement` we can write some Structure_Engine methods that basically offset perimeters etc. making use of some of the existing methods 
- This is owned by a `Bar` and `IAreaElement` as a `Fragment`

2. Rebar Detailing
- The `Rebar` makes use of the `IReinforcementBar` interface so inherits the properties that are common across the two representations
- Although it will have a spacing parameter and a shape code that it owns making it more refined 
- We need to be able to construct the various shape codes based on the `eNum` but right now the `ICurve` can define the bar whilst we map out various constructors
- The `RebarSet` is useful for downstream applications such as bundles of bars, but happy to use `tags` and other native BHoM properties to reduce additional object definitions 
- I think we should make some allowance for fire rating of the concrete, perhaps another fragment

![image](https://user-images.githubusercontent.com/30078587/118005313-2ed73000-b342-11eb-8f75-f57139eb2dd3.png)

@pawelbaran @al-fisher @IsakNaslundBh @alelom @rwemay

**Comment by pawelbaran** [comment]
Hmm, and what do you think about creating `ExplicitReinforcementBar` and using it with explicit layouts instead of creating intent-specific objects such as `LongitudinalBarIntent`? I imagine it as follows:
- two types of fragments: `RebarIntent` and `Reinforcement`
- both of the above containing a list of `IRebarSets` (or something like `IRebarEntity` that would be an interface for both individual bars and sets)
- thanks to the above, both fragments could share the features, starting from drawing individual bars by hand (`ExplicitReinforcementBar`) to automated generation of entire bar layouts
- in longer term we could even think of methods to convert hand drawn (imperfect) intents into layouts - or am I being too optimistic?

Regarding `RebarSet` vs `tags`, I would strongly opt for the latter for two reasons:
- less data: it is cheaper to store a bar definition only once, plus its distribution vector
- interop: most (all?) of the software packages support rebar sets, so it will be easier to talk to them

I know that it is one level below the discussion here, but let's not forget about the great work done by @LMarkowski in https://github.com/BHoM/BHoM/pull/1192 - even if the PR does not get merged, it will definitely be a source of inspiration!

**Comment by LMarkowski** [comment]
I'm a bit unsure if `Structure_oM` is a correct place for intents and detailing. In my understanding structural objects should be purely analytical, based on calculations, percentage of reinforcement etc. Then it's for methods like `Engine.Structure.Query.ReinforcingBars()` to depict that analytical reinforcement in form of physical `IReinforcingBar`s. Therefore Intents and Detailing could sit in `Physical_oM` as well.
But that's just my subjective opinion. 😄  I won't block it if I'm in the minority.

**Comment by peterjamesnugent** [comment]
@LMarkowski to answer your question, `ReinforcementDensity`, `BarRequiredArea`, `MeshRequiredArea` and `RebarIntent` (which will comprise of `IBarReinforcement` and `PanelReinforcement`) will also sit in the `Structure_oM` because they will be owned by `Structure` objects. However, the indepedent ReinforcementBar (currently `IReinforcingBar`) will be in the `Physical_oM`.

I've mapped out the existing implementation of rebar and the changes to be made (in green). Happy to discuss @IsakNaslundBh  @pawelbaran so it aligns with earlier discussions.

[Also saved here.](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/03_Code%20analysis/DiagramUseCaseDrafts?csf=1&web=1&e=mObri7)

![Reinforcement](https://user-images.githubusercontent.com/30078587/122654392-ef6ee100-d142-11eb-9c6e-af367899d13b.jpg)

**Comment by peterjamesnugent** [comment]
@pawelbaran discussion:
`Structure_oM`:
- `MinimumCover` parameter on `Panel` should be split in to a domain to allow different covers on each side - having a single parameter does not give the whole story (e.g. for a wall with an internal face and external face)
- `MetaData` object to be stored within `RebarIntent` object - see https://github.com/BHoM/MidasCivil_Toolkit/pull/299
- Orientation on `PanelReinforcement` is to allow for future development of a cylindrical basis - as opposed to using a `Vector`

`Physical_oM`:
- Further to discussion on how we represent the bars `Centreline : ICurve` vs `Orientation : CoordinateSystem`
- How to best make use of `RebarSets` so objects do not become bloated
- Link to representation table: https://github.com/BHoM/BHoM/pull/1247#issuecomment-850403519

**Comment by IsakNaslundBh** [comment]
Some initial comments:

1. Would not put miniumCover on the elements as a primary property. A cable or a steel plate with minimum cover just does not make sense, same way `FabricationType = Welded` does not make sense for a concrete beam.
1. A bit hesitant towards the gains/needs we get from moving the Reinforcement of the concrete section for Bars? If we keep it there it has the benefit of not having to be a fragment, but instead a primary property (easier to work with in general). It also feels kind of section related to me. This also removes the point mentioned above, if we keep the minimum cover here.
1. If not 2., then related to 1., would probably move the minimum cover to the RebarIntent class
2. Think it might be worth Having separate RebarIntent classes for Bars and Panels (if we keep them). Can still have a top level interface above them, but then add all the properties specifically needed for the two, and also enforce that a BarRebarIntet only contains BarReinforcement and vice versa for Panel
3. Even if we keep the reinforcement for the bars on the concrete section, could still se the benefit of making use of the rebar intent class as a middle layer, if useful, instead of just having a list of reinforcement on the concrete section. Means an extra layer, but if useful am not against it.
4. Not sure about the reason for the `MetaData` ? Why is that of extra importance for RebarIntent specifically? 

Have not looked through the panel and physical oM yet, but will do as well! Posting this in the mean time

**Comment by IsakNaslundBh** [comment]
To add, related to 2.,  if moving the reinforcement off the section to a fragment of the Bar is made for a of symmetry to the panels, so you always find it in the same place on the element, whether it is a panel or a bar, I can probably get behind that.

**Comment by IsakNaslundBh** [comment]
Some initial comments on the Panel reinforcement:

1. No minimumcover on the Panel, same as for bars
2. Think the general set up with the region looks good, including the orientation
3. Wonder if the `PanelReinforcement` need a few more parameters? Either as a duality in the properties for primary and secondary direction as in 2 spacings, 2 depths and 2 diameters? Alternatively, it could have some enum specifying Primary vs Secondary direction. But some thing would be needed to control it there.
4. For symmetry reasons mentioned above, wonder if it is worth exploring storing of the reinforcement on the Property of the panels, rather than as a fragment, but, that probably does not make that much sense for a panel. THink what you have done with the fragments seem more sensical.

Physical_oM:

Understand that this is a bit in flux yet.

1. As discussed on Teams, would change the shape code setup to work in a similar manner to the section profiles, with one class per type. Can either make them immutable and store the curve, or mutable and only store the parameters and the coordinate system and have a method to generate the curve.
2. Would like to understand the intended relation between the RebarSet and Reinforcement?
3. Not sure I understand the BarMarkId and MillTestId? Not saying get rid of them, but not fully getting their purpose?

Looking forward to our chat later!

**Comment by peterjamesnugent** [comment]
Thanks @IsakNaslundBh, I've included some explanation below where possible, and will update this comment following the meeting later.

`BarReinforcement`:
1 - 4. Agree on your reasoning for keeping `BarReinforcement` on `ConcreteSection`. So the `BarReinforcement` becomes its own class, whereas the `PanelReinforcement` is a `Fragment`, and both of those sit under an `IElementReinforcement` interface.
5-6. The idea behind the `RebarIntent` object was to mirror the rebar intent sketches, rather than having a flat list of `IBarReinforcement`. The `MetaData` was to introduce some traceability to the intent, perhaps an author, date, design stage etc.

`PanelReinforcement`:
1. Agree
3. We used an `Orientation` on the `PanelRegion` to allow for the future addition of a cylindrical coordinate system - so I wonder if there's a clever way to allow for that without constraining ourselves to orthogonal reinforcement with primary and secondary?

`Reinforcement`
1. Yup, lets discuss coordinate system vs curve on the call later.
2. The `RebarSet` was to contain many `Reinforcement` bars and even own some of the properties so that it would not be stored 1000s of times and duplicates (imagine a large slab in a warehouse for example. 
3. These are just placeholders to demonstrate that we can store ids from downstream in the process as a fragment with relative ease.

**Comment by IsakNaslundBh** [comment]
> The MetaData was to introduce some traceability to the intent, perhaps an author, date, design stage etc.

Not sure why reinforcement is so special here though? Would not the size of the section, or even location of the element be of at least as high importance then? Not against being able to trace this, but would then rather have it as a fragment that you could attach to anything I think, rather than a primary property of a quite deep object in the hierarchy.

> We used an Orientation on the PanelRegion to allow for the future addition of a cylindrical coordinate system - so I wonder if there's a clever way to allow for that without constraining ourselves to orthogonal reinforcement with primary and secondary?

My main point is that what does the spacing mean? In what direction will the reinforcement run? for cartesian, is it always local x? How do you then introduce reinforcement along local y? We need something there to determine this.

For cylindrical coordinates it could still work with primary and secondary I think, with a convention as Primary = radial and secondary = circumferential or similar. The `Spacing` property for radial would need some thought for that case though. Maybe it just should be defined in radians for radial reinforcement or something like that (which we should be able to state on the description of that property if we go down that route)

**Comment by peterjamesnugent** [comment]
My thinking was that you would use the `ReinforcementRegion` local x for direction and local y for spacing.

This would mean you would need two `ReinforcementRegion` objects with the same defining curve with different Orientations though, this does allow full flexibility but could get messy. Also, would be difficult to make it work for cylindrical coordinate system.
