### ISSUE TITLE
Structure_oM: LoadCombination is not compatible with Reflection.Query.DistinctProperties due to use of tuple.

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM#1287]
In [SAP2000 issue 215](https://github.com/BHoM/SAP2000_Toolkit/issues/215), I found that DependencyTypes was not properly handling `LoadCombinations`, which are dependent on `Loadcase`, because the `Loadcase` is stored in a tuple, and Reflection.Query.DistinctProperties() requires each dependent object to be stored as it's own type. As I see it, this should either be solved by flattening the `LoadCombination` tuple so that the cases and factors are stored separately, or by making a sub-object `LoadComboRecord` which can be tracked as a dependency.

**Comment by FraserGreenroyd** [comment]
From my experience in Environments, trying to keep track of 2 separate lists can quickly turn into a nightmare. I would advocate for a `LoadCombinationRecord` object so you can tightly marry the two properties together.

_This is assuming that A) `flattening the LoadCombination tuple` did mean separating it into two lists and B) that the properties of `case` and `factor` are required to be tightly knit - if either of these assumptions fails, this entire comment is likely to not be very helpful - so I'm adding these assumptions in so you can determine how useful such the comment of support for `LoadCombinationRecord` is from a non-structures perspective!_

**Comment by IsakNaslundBh** [comment]
@JosefTaylor I am aware of this issue, and actually raised a PR to try to fix it just a few weeks ago:

https://github.com/BHoM/BHoM_Adapter/pull/305

The alternative would be to make a change to the DistinctProperties method to also look into `List<Tuple<double,P>>`, but that got to the point of being quite a few steps to specific, hence the tweak to the adapter is my preferred choice.

Would _not_ want to separate the data out into separate lists thought, as I think that is a recipe for disaster in terms of keeping track of everything, and for hard to notice bugs to make their way into it.

There are some other options this can be handled by in oM/Engine, such as adding a CaseFactor class or similar instead of the Tuple (could then have a dependency chain of Combo -> CaseFactor -> LoadCase) but prefer the solution in the PR anyway. Would be great if could you have a look at it, but would want @alelom s approval as well as it is a tweak to the base adapter.

**Comment by JosefTaylor** [comment]
Believe BHoM_Adapter#305 closed this issue!
