### ISSUE TITLE
Documentation URL No Longer Valid Post Directory Reorganization

### ISSUE THREAD

**Issue by travispotterBH** [BHoM/BHoM#1570]
https://github.com/BHoM/BHoM/blob/a4c48079558ce4d29ce32a28f22236fd83d2eeb6/Structure_oM/Elements/Bar.cs#L41

One such example. Worthwhile to do a review for all: 
https://github.com/search?q=repo%3ABHoM%2FBHoM%20https%3A%2F%2Fbhom.xyz%2Fdocumentation&type=code

https://github.com/search?q=org%3ABHoM%20https%3A%2F%2Fbhom.xyz%2Fdocumentation&type=code

**Comment by travispotterBH** [comment]
After edits to [documentation structure](https://github.com/BHoM/documentation/pull/92), many places now reference invalid urls

**Comment by FraserGreenroyd** [comment]
Hi @travispotterBH , that is already a part of the overnight checks the bot does, alongside testing and installer builds. It's just a dashboarding issue reporting that, and resource issue to actually resolve once noted across the areas once highlighted, particularly as we're mid-sprint for the final features, this will likely get picked up next sprint during testing so that it's done before the beta 👍
