### ISSUE TITLE
BHoM: Do we need BHoMGroup ?

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM#255]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by parched** [comment]
I'm interested to know whether I should use this rather than `List`, but I don't have permission to view the archive. What was the conclusion?

**Comment by adecler** [comment]
The only real benefit of `BHoMGroup` is to provide a `List` that is also a `BHoMObject`. I personally never used it so you are safe to use `List`. 
`BHoMGroup` seems to be mainly used in Structure so maybe @IsakNaslundBh can given you more insight.

**Comment by IsakNaslundBh** [comment]
> I'm interested to know whether I should use this rather than `List`, but I don't have permission to view the archive. What was the conclusion?

For most cases a List is enough, and preferred over a `BHoMGroup` due to being simpler.

In the structure space the `BHoMGroup` is currently used for two things:
1. The create named groups that can be pushed through adapters. For example a `BHoMGroup` of bars could be named "Roof main beams" and pushed over to a package for simpler identification of the Bar objects in that group in the software.
2. Load application. This is a bit related to 1.. Some software packages allow for load to be applied to named groups (as defined above). With a `BHoMGroup` on the loads it means that for some workflows you can simply state the name of the group to be loaded rather than filtering out the elements to be loaded when pushing to a package. This can lead to simpler workflows in some cases, for some packages.

There might be other use cases throughout the BHoM as well that I am not aware of. But Would use a `BHoMGroup` if I wanted a generic list that is a `BHoMObject` and has a name. For all other cases (which probably will be most cases) I would just use a `List<T>`. For example the Panel class owns a `List<Edge>` and `List<Opening>` for its internal edges and openings, as there would be no real gain for the collections themselves to be `BHoMObject`s for that case.
