### ISSUE TITLE
BHoM: Rename CustomData Property

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM#325]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
Is that something we still want to do ? I am fine either way but wondering if the cost of such a change is not too big for its worth

**Comment by al-fisher** [comment]
I think a step before renaming should be completed first (which may also make any renaming less impactful - well in the code at least)  if we would decide to go ahead.

Discussed before that _all_ occurrences of the use of CustomData in the code should arguably be replaced with a formalised fragment now. In particular in the adapters etc.
However I know we have also at times spoken about an argument for the case of still having a `string` keyed `Dictionary` on the BHoM Object for use in the code - as well simply included for exposure to the user. 
Reclarifying uses (in parallel to fragment) is important now, and I think this for me is where the informality of a name Like `UserData` may or may not help depending on what we are wanting to encourage.

I suggest we do a reporting exercise of all instances of `CustomData` currently in the code - to help us make a decision about any cleaning up still needed and also if any subsequent renaming is still desired.

What do you think?
@adecler @alelom @IsakNaslundBh @FraserGreenroyd

**Comment by adecler** [comment]
After a quick search, here are the main culprides:
- Adapters (mainly AdapterId)
- Climate Change
- Revit Toolkit

Those 3 should all be moved to fragments without much trouble (already in motion for the adapters I believe). 

As discussed in the past, `CustomData` should ideally be called `UserData` as it should ideally only be used by the end user, never directly in the code. I don't remember a conversation with arguments in favour of using `CustomData` in the code but I would very much like to know the pros for that as I cannot think of a single one where it is a better option than using fragments.

There is also the question of turning the `CustomData/UserData` into a fragment itself for conciseness. I have to say I have mixed feelings about that. On one hand, it makes things cleaner and simpler. On the other, some things are worth keeping separate in order to highlight them better to the user (like we did for `From/ToJson` or `Set/GetProperty` components).

**Comment by al-fisher** [comment]
> After a quick search, here are the main culprides:
- Adapters (mainly AdapterId)
- Climate Change
- Revit Toolkit
Those 3 should all be moved to fragments without much trouble (already in motion for the adapters I believe).

This is good. Thanks. Yep - agreed.

>  I don't remember a conversation with arguments in favour of using CustomData in the code but I would very much like to know the pros for that as I cannot think of a single one where it is a better option than using fragments.

I think the argument on this one was overhead and ease of fragment vs customdata. 
Fragments have developed further with the fragmentset - and in particular fragments are only forced to implement `IObject` now (although _can_ also be `IBHoMObject`). So storing say a single `double` in the code does not introduce lots of overhead (or indeed much more than wrapping to be stored in CustomData would anyway)
So agree.

CustomData could still be useful in code for prototyping - but I would put that in the same use case as "UserData" anyway - just added in code rather than flow based environment. With aim to formalise if code widely adopted. 

> There is also the question of turning the CustomData/UserData into a fragment itself for conciseness.

On this - I think we do keep both separate - as Custom/UserData (a simple Dictionary<string, object> is a genuine different use case to Fragments.

**Comment by adecler** [comment]
From @pawelbaran : 
- need to improve getProperty method to also look into fragments

**Comment by adecler** [comment]
- @FraserGreenroyd to list where CustomData is currently being used and coordinate the effort around getting rid of it.
- @IsakNaslundBh to try to get CustomData to be removed from the Structure side.
- @alelom to assist on coordination around adapters.
- @adecler to make sure fragments are capable of replacing the CustomData in term of ease of access in the UI and `GetProperty`.

**Comment by FraserGreenroyd** [comment]
Have assigned myself so I remember this for the action attributed to me! :smile:

**Comment by FraserGreenroyd** [comment]
I have prepared a script which will search for instances of `.CustomData` within code, and will raise issues on repos as appropriate.

BHoM_Engine will be split into per-engine issues to allow for easy resolution by relevant engine code-owners. Other repos will receive one issue listing all files that are using `CustomData`.

The body of the issue will be:


 > The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

 > This is to be completed by **Friday 30th October 2020**.


Following this will be a list of the files in which `.CustomData` is identified as being in use that people can use to check off when they're happy they have rectified the file.

I will start raising the issues over the weekend, to give everyone a clear week of sprint 2 to understand them/raise questions, and the first week of sprint 3 to then rectify them.

**Comment by adecler** [comment]
@FraserGreenroyd , @pawelbaran , I had a look at the `Revit_Toolkit` since it has often been mentioned as one of the repo requiring the largest amount of work to accommodate this change. There are only 13 lines of code in total that are referencing CustomData so that shouldn't be too hard on that level :smile:

Of course, there is the question of how to approach to take. This was my main reason for looking at the Revit toolkit so you are not left on your own during the execution. 

Here's how I see it. The "Properties" assigned to `CustomData` are as follows:

```
CustomData["Concrete Bending Reinforcement"]
CustomData["Concrete Shear Reinforcement"]
CustomData["Concrete Shear Strength Reduction"]
CustomData[Convert.CategoryName]
CustomData[Convert.Edges]
CustomData[Convert.FamilyName]
CustomData[Convert.FamilyPlacementTypeName]
CustomData[Convert.Meshes]
CustomData[Convert.RenderMesh]
CustomData[Convert.Surfaces]
CustomData[Convert.ViewName]
CustomData[Convert.ViewTemplate]
```

For each of them , you should create a Fragment with the same Type name. That way you work with those easily using methods like `AddFragment` and `FindFragment`. Soon, I'll also modify the `GetProperty` method so that it will return the value of the fragment whose type name correspond to the input name if it exists.

**Comment by FraserGreenroyd** [comment]
All issues raised and coordination done, everyone has until the 30th October to remove instances of `CustomData` in their code so that @adecler can then rename the property as desired. Any code still using `CustomData` on the 30th October will get a PR removing it as discussed, so hopefully everyone else will get it done before then.

@adecler I raised one issue on BHoM_UI but wasn't sure if it was valid, so feel free to close it if not needed. I detected uses of `CustomData` in Excel and Dynamo UIs, but opted not to raise issues as I figure that's part of the UI functionality and you'll refactor all of the UIs together when you rename the property.

I'm now unassigning myself as my part in this is now done and is assigned to issues on other toolkits to remove the `CustomData` usage as necessary.

**Comment by al-fisher** [comment]
Thanks all - plan above is looking great. So good to get the use of this and the fragments all nicely aligned finally.

**Comment by al-fisher** [comment]
As mentioned on call this morning though - any change to naming of `CustomData`, would need to be coordinated with the `CustomObject` 

The pairing of these two concepts is a really important part of explaining the extensibility of the BHoM.

I thought we had discussed this historically - and digging into the archive there was some mention of this already about needing to coordinate with the CustomObject and some other discussion of alternative names.

---

<details>
<summary>Historic chat</summary>
<p>


**https://github.com/BHoM/BHoM/issues/325 - rwemay**
Putting this out there/up there. Some time ago we mooted renaming CustomData to something more 'permanent' or 'formal'. I don't remember if we had any agreement on a) changing it or b) what to, but raising this for record with some options.

ExtendedData
DynamicProperties
ExtendedProperties
Thoughts welcome! Obviously this is a major change, so it should happen this side of O/S, I guess.

@al-fisher , @adecler , @IsakNaslundBh

**https://github.com/BHoM/BHoM/issues/325 - al-fisher**
New name needs to be defined to play nice in context of the other classes of Properties on the object such that the difference is clear. Previous notes in Wiki dug out for ref and then potential review/update defining-properties

We have: Defining Properties of the Object set in the oM Derived Properties queryable from an Engine Method

I therefore like Extended Properties - referencing the ability to attach any additional data beyond the above two classes of properties. And speaks to Extensibility. Dynamic feels a little loaded (@adecler I can't remember did we discuss this last one already?!)

Finally terminology will also need to sit alongside any future possible formalisation of the ECS on the base BHoMObject https://github.com/BuroHappoldEngineering/BHoM/issues/293 Not sure how we would refer to these in future - I suppose these would still be either Defining, Derived or Extended Properties of the corresponding Modular/Entity Components of the object. But some form of Modular Properties as a term?

**https://github.com/BHoM/BHoM/issues/325 - adecler**
I would actually push the other direction 😏. I would suggest keeping CustomData ONLY for the dynamic information added by the user. Admittedly, this means we could rename that UserData. But then, we should also rename CustomObject to UserObject.

For everything done in the code (mainly adapter stuff I guess), we could use a type-strong storage system in the spirit of Entity-Component-System. I have used that in the Human class already where the class is defined with a single property:

public List<IHumanRole> Roles { get; set; } = new List<IHumanRole>();     
We can them attached as many oles as we want to the class such as Employee, Skeleton and GitHubUser.

We could extend this by giving the ability of owning Roles to all BHoM Objects. In the example of the Revit Adapter, we would have a RevitElement : IRole role that we could attach to any object instead of flooding the CustomData dictionary.

Now, there is the question of using a List or a Dictionary...
Speed not really being the main concern here, we need to consider how we are going to expose roles in the UI. Do we do the same thing as for CustomData? In that case Dictionary is something we know the mechanics and pros & cons of (need to provide a name and risk of clashing but really friendly for the UI). So I would tend to favour that.

We could just use a list and exposing as outputs the properties stored inside the roles instead of the roles themselves but that is a bad idea. A lot of roles will have clashing property names (like "Name"). So having a single "Name" output that contains the "Name" property of the object itself and the one of all its roles in an arbitrary order is confusing.

So a new property like this seems nice:

public Dictionary<string, IRole> Roles { get; set; } = new Dictionary<string, IRole>();     
But this needs more discussion. The points raised above are just from the top of my head.

@IsakNaslundBh , @epignatelli , @al-fisher , @rwemay , what do you think ?

**https://github.com/BHoM/BHoM/issues/325 - rwemay**
Is 'roles' and ECS term? I think I get it in terms of a function or part played by an object/person. It is a little confusing to me once you get to the detail - is Skeleton a 'role'?

In any case I think we're saying a similar thing in that data added by a user on the fly to pass around flow based VP scripts need to be a different property to the more formal properties needed by adapters.

Hope I'm understanding correctly, probably needs a Skype convo when we've time!

</details>
</p>

--- 
As raised this morning though by @IsakNaslundBh and @adecler not sure any possible names map especially well to the Object concept - even _**UserObject**_ is not quite right as a name really.

The benefit of removing use of CustomData in code in favour of type strong fragments is clear (leaving CustomData just for volatile use in scripts) 
Benefit of actually renaming (unless anyone can come up with a real winner!) is little less clear. 

@adecler @IsakNaslundBh  FYI

**Comment by al-fisher** [comment]
Following above - suggesting sticking with the paired naming of `CustomData` along with `CustomObject`

Good to get others thoughts and get agreement around this in the next couple of days to close out/plan remaining CustomData tasks

**Comment by IsakNaslundBh** [comment]
> Following above - suggesting sticking with the paired naming of CustomData along with CustomObject

would agree on this. Think those names make most sense.

**Comment by alelom** [comment]
> Following above - suggesting sticking with the paired naming of CustomData along with CustomObject

agreed. I prefer "Custom" rather than "User", and the removal of most of its usage in favour of Fragment made things clearer at the framework level.

**Comment by FraserGreenroyd** [comment]
We also have a Compliance Check waiting to be added once this discussion is closed out (https://github.com/BHoM/Test_Toolkit/issues/281) which will help ensure we don't sneak CustomData back in if we choose to keep the name, so I'm happy with keeping the name if that's the consensus, and I have no qualms either way. I dislike CustomData for the reasons previously stated in code, but agree with it making the most sense for the workflows we've discussed and its capacity to store volatile data in the right circumstance :smile:

**Comment by adecler** [comment]
>Following above - suggesting sticking with the paired naming of CustomData along with CustomObject

Agreed

**Comment by adecler** [comment]
Closing as CustomData name will not be changed
