### ISSUE TITLE
Structure_oM: Structural materials revamp

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#399]
As a part of the general Material updates here https://github.com/BHoM/BHoM/issues/393, would good to also rewamp the structures part of the materials.

First sketch of class diagram below

![image](https://user-images.githubusercontent.com/22005920/51840612-cbf63200-230c-11e9-9b32-cc10bebfa94c.png)

**Comment by JosefTaylor** [comment]
Speaking of multiple structural properties for a given material, how should we handle nonlinear material models? I can imagine a given grade of steel having a complete set of linear properties (Young's Modulus and Poisson's Ratio) and a separate, also complete set of nonlinear properties in a given model, i.e. bilinear hardening.
I see a few options:

1. Each real material is represented by a single BHoM material, containing several models (for thermal modeling, linear FE, nonlinear FE, etc.) which are chosen depending on the needs of the modeler.
2. Each real material is represented by a number of BHoM materials, each with only one set of properties, so there might be "A490" and "A490 - Bilinear Strain Hardening"
3. Each real material is represented by a single BHoM material, containing only measurable properties (but ideally including plastic properties as well). Nonlinear models are then created based on this information (this part can be sticky)

**Comment by rwemay** [comment]
Some great comments here. On damping, something on the base class would be OK provided that it is constant for all frequencies/time steps. On concrete class: yes definitely cylinder/cube designation needs to be referred to. On reinforcing steel, we should be clear whether the base material being defined is concrete, or reinforced concrete (a composite). I would suggest creep, shrinkage are parameters in design modules/classes as they change quite a bit per code. 

For non-linear structural materials, I would suggest these are separate, perhaps through an interface to the base material. They will indeed require time/strain dependent functions and lists rather than individual properties.

**Comment by JosefTaylor** [comment]
Then again, perhaps if we are moving a standards defined material (i.e. ASTM A992 Gr. 50) then we should only be specifying the parameters defined by that standard, rather than a bunch of things we're extrapolating or testing.

@peterjamesnugent when you say 'strength for concrete, stress for steel'; why is that a convention? I'm not sure I've seen that explicitly before.

**Comment by IsakNaslundBh** [comment]
Great comments by all.

@peterjamesnugent I used https://www.xmind.net/

Kind of liking @JosefTaylor s last suggestion. Could have a ISteelMaterialModel for example, that the steelclass then can own.

If there are properties that exists in ALL required models we could move them to the steel class, but if not, all values would be contained in the various models we can pre define.

Could be based on various codes/other requirements as we like.

Bad thing about doing something like that would be how well it would work with the adapters, as we don't want to end up in a situation where we have to write separate material converters for every available code for every available adapter if we can avoid it..

**Comment by IsakNaslundBh** [comment]
Also @peterjamesnugent the concrete section has a reinforcement proeprty, not used that much/at all yet that definitely needs updating. Need to make sure to not overlap the yield stress there compared to any material properties.

Could see benefits in both approaches.

**Comment by JosefTaylor** [comment]
Yes, a reinforcement in a concrete material or a concrete section should reference a steel material, not just stick a yield strength in.

**Comment by peterjamesnugent** [comment]
> @peterjamesnugent when you say 'strength for concrete, stress for steel'; why is that a convention? I'm not sure I've seen that explicitly before.

I have just checked the Eurocode and it uses strength instead of stress in both the Steel and Concrete codes, not sure why I thought the opposite in my previous comment.

Agree on referencing steel material rather than just f_yd for reinforcement.
