### ISSUE TITLE
Geometry_oM: ISurface geometry and IObject2D

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/BHoM#422]
It seems we are missing definitions of ISurface objects which can handle IObject2D geometry.
* Extrusion gives rectangular shape only (if extruded from line)
* NurbsSurface does not fully implemented in BHoM and cannot handle openings

![image](https://user-images.githubusercontent.com/16777757/53746639-8db6da00-3e99-11e9-89f5-ee580e10edb6.png)

![image](https://user-images.githubusercontent.com/16777757/53746663-9f987d00-3e99-11e9-829d-047826d0a682.png)

**Comment by IsakNaslundBh** [comment]
Yes, think we need a surface class with more capabilities than what we have atm. A surface class with an underlying NurbsSurface and cutting curves could potentially work?

**Comment by al-fisher** [comment]
Yes - agreed - we ultimately need a trimmed NurbsSurface to be fully implemented at some point. 

In advance of that, wondering if it is worth creating another class of surface perhaps `PlanarSurface`?
 
A new `PlanarSurface` can be simply defined by planar curves? This will likely be used much more often than fully free-form Nurbs surfaces.

Not too dissimilar to how we have split the concept of `PanelPlanar`or`BuildingElement` and their `PanelFreeform` counterpart. The planar element is then defined simply as two Lists of `Curves`/`Edges` for the boundary and the internal openings.

It will also then allow definition of a simple surface like the above example without having to convert to degree 1 flat Nurbs with redundant weights and knot vectors.

Then, as and when we implement full trimmed Nurbs we can plan to consolidate the concept of the PlanarSurface and the trimming curves in UV space of the Nurbs. Depending of implementation of our Trimmed Nurbs.

Thoughts?

**Comment by al-fisher** [comment]
@pawelbaran - adding you into this conversation too.

**Comment by pawelbaran** [comment]
I would dare to say that we should not bother about the non-planar panels for now:
1. They are extremely rare cases, possibly handled only by superusers (who then can handle them with some smart workarounds).
2. We are still missing basic implementations covering planar object - I would put all effort into finishing these before we go anywhere further.

Following the above, I would opt for adding `PlanarSurface`, at least for the time being.

**Comment by rwemay** [comment]
Agree on separating planar from non planar surfaces to reduce overhead on creating agnostic methods and extensions. 

I think we should also separate engine dev from oM dev to some extent, so that interop isn’t held up. Making sure there’s an object to convert geometry to/from things is a big (and relatively easy) step and unlocks a lot of workflows. So what if nurbs methods arent available if you can pass them through sockets to use another software to manipulate (eg Grasshopper).

**Comment by al-fisher** [comment]
Great - sounds like we are in agreement. Will raise an issue for creation of new class.
@IsakNaslundBh following our discussion also - hope happy - can you together with @ZiolkowskiJakub @pawelbaran agree who will action close out of this. Thanks

**Comment by IsakNaslundBh** [comment]
Yes, agreeing on all points being made. 

Could now to start with add this PlanarSurface objects, as should be quick to do. Then following @rwemay s comment, I fully agree on this. We should sooner rather than later add a oM definition of a TrimmedNurbs sooner rather than later, even if we literally have 0 methods supporting it in the engine, for interop purposes.

**Comment by al-fisher** [comment]
Perfect. I have created the above issue - labelling as non-critical.

**Comment by al-fisher** [comment]
Closing this issue as agreed actions successfully raised as issues and PR and closed out.
