### ISSUE TITLE
Structure_oM: Node supports

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/BHoM#446]
Two alterations required

1. Currently there are two methods for creating support nodes, using either point or coordinate system. I think the point method should be removed as providing the coordinate method with a point will use the global coordinate system.

2. Coordinate system method does rotate support to match axis, rotation angles need using and applying in analysis, not sure if this is BHoM issue or Robot toolkit issue.

**Comment by IsakNaslundBh** [comment]
To answer this:

1. This is really an Engine issue, but, the reason for keeping both was so that old script would not break and to make it clearer for people using the toolkit that you could create a node from just a point and do not need to provide a full coordinate system. If the majority feel that it is clearer to only have the create method that takes a coordinate system and is able to cast a point into just that, I would be fine with deprecating the old method.

2. This is a Robot issue. Issue for it opened here: https://github.com/BHoM/Robot_Toolkit/issues/212

**Comment by IsakNaslundBh** [comment]
Closing as main issue is for Robot. @jdarcyBHE feel free to reopen if you disagree.
