### ISSUE TITLE
Reflection_oM: Add Fragment attributes

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#478]
A series of attributes to be added to be used on `Fragments`. Names below to be confirmed:

- `FragmentDesignation` - Stating which object/interface that this fragment can be applied to
- `UniqueFragment` -Stating that only one of this fragment type can be applied to the specific objects.
- `DefiningFragment` - Stating that this fragment should be seen as something with as high significance as a primary property of the object it is attached to.

Attributes to be used by various engine methods to try to ensure that the fragments are used and assigned correctly

**Comment by alelom** [comment]
Ties well with https://github.com/BHoM/BHoM/issues/552

**Comment by adecler** [comment]
Should we handle this this quarter?

**Comment by al-fisher** [comment]
Yes please - think we should

**Comment by FraserGreenroyd** [comment]
Do we have a road-map plan for handling this in a coming quarter (recognising that we ended up changing the plan to include it in 3.1)? :smile:

**Comment by adecler** [comment]
I guess that's a common problem with issues assigned to multiple people 😄 

Should we have a quick workshop or simply discuss here for refining the details and actions ? Her few comments to start the conversation:
- `FragmentDesignation` : might be just me but I would prefer something a bit clearer / straightforward like `FragmentTarget`.
- `UniqueFragment` : aren't all fragment unique by definition (since we are using a `KeyedCollection<Type, IFragment>`)
- `DefiningFragment` : can you give example of where this would apply ? My theoretical understanding was that something that is a defining part of an object is a property of it. If it isn't essential, then it is a fragment. So any fragment that would have that attribute should be a property, right ?

**Comment by FraserGreenroyd** [comment]
> I guess that's a common problem with issues assigned to multiple people

Agreed :smile: I found it in my to-do pile so thought I might as well prod a little!

Do we have an upcoming framework meeting that this could be an agenda item for perhaps? I suspect there's some meat to the discussion that might make a workshop easier for refining details and actions? I could see an issue for one on the 9th April but not one for May/upcoming weeks?

**Comment by adecler** [comment]
> Do we have an upcoming framework meeting that this could be an agenda item for perhaps?

We have now: https://github.com/BuroHappoldEngineering/BuroHappold_admin/issues/163
Thanks for the reminder :smile:

**Comment by adecler** [comment]
From our discussion:
   - FragmentTarget -> still relevant I think
   - Unique fragment mean we can force uniqueness by iterface
   - DefiningFragment -> the purpose was to have the fragments coming as output of the explode which is not possible for speed reason (objects are grouped by type before extracting the output, we cannot do that anymore of fragments are outputs since you have to process every single object)

**Comment by adecler** [comment]
Related issue: https://github.com/BHoM/BHoM/issues/552

**Comment by rwemay** [comment]
Just a thought on this and following conversations yesterday. Is it possible for us to tag a fragment with IImutable and then have some exceptions on SetProperty(). For example if SetProperty() is used on an object that has an IImutable fragment, the fragment is removed and a warning set back to the user? From @adecler 's comments on performance, sounds like this might be tricky.

**Comment by adecler** [comment]
As discussed in the Framework workshop:

- FragmentTarget: for the UI to add check ? Should be devolved to utility methods in the Reflection engine instead. Probably to be solved next quarter, not this one. 
- Unique fragment: should be informative instead of enforcing. Can have a few utility method like `SafeAddFragment` that would do the checks for you. Otherwise we need to devolve the responsibility to the developer when they add the fragment.
- DefiningFragment: would be a valuable one to have this Quarter. @IsakNaslundBh and @FraserGreenroyd to provide concrete user cases before action though.

Will need to provide more concrete cases before any action.

**Comment by adecler** [comment]
>@IsakNaslundBh and @FraserGreenroyd to provide concrete user cases before action though.
Will need to provide more concrete cases before any action.

@IsakNaslundBh and @FraserGreenroyd, can you provide concrete cases for the usage of the new fragments above ?

**Comment by IsakNaslundBh** [comment]
> @IsakNaslundBh and @FraserGreenroyd, can you provide concrete cases for the usage of the new fragments above ?

One concrete use case would be `Concrete` 😃 . All IMaterialProperties in structures and Environments should be made into fragments, and should be defining fragments.

Have just not happened yet due to time and coordination, and was not done straight away due to the then lacking support for fragments in the UIs. That would be my primary example.

**Comment by FraserGreenroyd** [comment]
Environments don't have any defining fragments for our objects, they are very much fragments which are nice to have but not essential. At least in terms of the current fragment sense.

To link with @IsakNaslundBh though, our `SolidMaterial` and `GasMaterial` objects are `IMaterialProperties` and are defining data to a `Material` for Environmental workflows, which should become fragments once the switch over to them becomes done.

Sorry can't be of more help on this one from the Environments side, we generally only use fragments as the extra nice-to-have but not-defining capacity :smile:

**Comment by adecler** [comment]
Despite the examples,  I am still unclear as to why a defining fragment should not just be a property. Especially given that only one of the two disciplines seems to actually need this attribute. 

Best is to probably have a chat at this point.
