### ISSUE TITLE
DataManipulation_oM : Rename Queries to Requests

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#499]
`IQuery` and `Query` objects need to be renamed to avoid confusion with the `Engine.*.Query` class. Agreed proposal was to rename as `Request`

**Comment by ZiolkowskiJakub** [comment]
Hi @epignatelli,

Here is Revit_Toolkit issue for this: [Revit_Toolkit](https://github.com/BHoM/Revit_Toolkit/issues/318)

**Comment by epignatelli** [comment]
Thanks @ZiolkowskiJakub, I'll check before lunch what repos are actually breaking and post a list in here.

**Comment by IsakNaslundBh** [comment]
Question for the `FilterQuery`. If we aim longterm to get rid of the Equalities Dictionary in there (should not be done now), should it be renamed `TypeRequest` ? Might be something we will want to do at a later point.

**Comment by epignatelli** [comment]
To summarise the changes:
- `IQuery` into `IRequest`
- `BatchQuery` into `BatchRequest`
- `FilterQuery` into `FilterRequest`

An example of transition in the actual code is:
`public override IEnumerable<object> Pull(IQuery query, Dictionary<string, object> config = null)` to
`public override IEnumerable<object> Pull(IRequest query, Dictionary<string, object> config = null)`

or 

`m_linkIn.SendData(new List<object>() { PackageType.UpdateProperty, new Tuple<FilterQuery,string,object>(filter,property, newValue), config, RevitSettings });` to 
`m_linkIn.SendData(new List<object>() { PackageType.UpdateProperty, new Tuple<FilterRequest,string,object>(filter,property, newValue), config, RevitSettings });`

Given the number of projects affected, speak now if something doesn't work for you.



---
Guys, the one below is an automated dependency check to start with, so take it with a grain of salt. I am 95% sure that if a repo is in the __breaking repos__ column, it breaks.
I am 50% sure that if a repo in the "non breaking repos", does not actually break. This is because it may depend on a project that breaks. 
I am going to manually check them tomorrow, but this should be a good indicator.
Note that this checks also `*_Test` projects in the solution file.

I've put some names beside the repo name as a candidate for making the changes, but if that doesn't work for you, let me know, I'll take care of it.

Action required
--

- [ ] BHoM_Adapter @alelom 
- [ ] BHoM_Engine @epignatelli 
- [ ] BHoM_Installer @awakeman 
- [ ] BHoM_Test @epignatelli 
- [ ] BHoM_UI @epignatelli 
- [ ] Chrome_Toolkit @adecler 
- [ ] Civil3D_Toolkit @Conor-Hubert-BH 
- [ ] Climate_Toolkit @tg359 
- [ ] Dynamo_Toolkit @ZiolkowskiJakub 
- [ ] EnergyPlus_Toolkit @tg359 
- [ ] ETABS_Toolkit @MartinHenriksen ?
- [ ] Filing_Toolkit @awakeman 
- [ ] Github_Toolkit @epignatelli 
- [ ] Grasshopper_Toolkit @epignatelli 
- [ ] GSA_Toolkit @IsakNaslundBh 
- [ ] HTTP_Toolkit @epignatelli 
- [ ] IES_Toolkit @FraserGreenroyd 
- [ ] LDAP_Toolkit @awakeman 
- [ ] Mongo_Toolkit @epignatelli 
- [ ] Radiance_Toolkit @FraserGreenroyd 
- [ ] Revit_Toolkit @ZiolkowskiJakub 
- [ ] Rhinoceros_Toolkit @epignatelli 
- [ ] Robot_Toolkit @alelom 
- [ ] SAP2000_Toolkit @JosefTaylor 
- [ ] Sharepoint_Toolkit @awakeman 
- [ ] Socket_Toolkit @epignatelli 
- [ ] SpeckleToolkit @alelom 
- [ ] StructuralEngineering_Toolkit @IsakNaslundBh This only references the `DataManipulation_Engine`
- [ ] TAS_Toolkit @FraserGreenroyd 
- [ ] XML_Toolkit @FraserGreenroyd 

Breaking repos only in their `*_Test` file:


**No action required**
---
Repos that potentially do not break:
- BHoM_Datasets
- BuildingEnvironments_Toolkit
- BuroHappold_Datasets
- CableNetDesign_Toolkit
- CodeAssistant_Toolkit
- CSharp_Toolkit
- CSV_Toolkit
- DataSetsMaintenance_Toolkit
- DataViz_Toolkit
- Excel_Toolkit
- FormFinding_Toolkit
- Kinect_Toolkit
- Lusas_Toolkit
- MachineLearning_Toolkit
- MidasCivil_Toolkit
- ModelLaundry_Toolkit
- MultiDisciplinary_Toolkit
- PostgreSQL_Toolkit
- RAM_Toolkit
- Residential_Toolkit
- RFEM_Toolkit
- S-Frame
- SecurityICT_Toolkit
- Tekla_Toolkit
- Topologic_Toolkit
- Unreal_Toolkit
