### ISSUE TITLE
Fragment vs CustomData lookup cost: should we have a Dictionary<Fragment> (or HashSet<Fragment>) instead of List<Fragment>?

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM#538]
### Description 

Every time you need a specific fragment stored in an object, having a `List<Fragment>` forces you to **iterate the list and filter out that fragment**.

This means that in order to retrieve a specific type of fragment you need to use a method that does just that: iterate the list of fragments, identify the right type, return that.

This has an unavoidable cost in terms of performance which is sensibly higher than the cost of a Dictionary lookup, [which by definition is close to O(1)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?redirectedfrom=MSDN&view=netframework-4.8#remarks). In this sense, `CustomData` is much more efficient, especially if you just need to store simple data (e.g. just a `string`, like with AdapterId)

### Practical example case
For example, in the Diffing_Engine I had to implement this [`GetHashFragment()`](https://github.com/BHoM/BHoM_Engine/blob/56e9d72a67018fcb33193eb1289040c0c99ff540/Diffing_Engine/Query/GetHash.cs#L13-L30) method just to retrieve the a specific `HashFragment` (and also, to make sure it was the only of its type among the other fragments).

After profiling the diffing, it's clear that [a high percentage of the computation is spent only looking for the HashFragment](https://github.com/BHoM/BHoM_Engine/issues/1119#cpu-profile).

### Proposal

After a chat with @al-fisher, we thought that instead of having a list of Fragments we might have a **Dictionary of fragments**, where the key is the fragment type and the value is the fragment object, such as:
```
Dictionary<Type, IBHoMFragment> Fragments
```

@al-fisher thought that in general we want to enforce that a certain type of fragment is not repeated in the Fragment list -- so this could also solve that.

Please comment with your thoughts.
@al-fisher @epignatelli @adecler @FraserGreenroyd @IsakNaslundBh

**Comment by epignatelli** [comment]
It all makes very much senses to me.
The only questions I have are:
- Are we sure that we cannot optimise and centralise the method that searches for a specific fragment to the level that its performance hit is negligible?
- In case we can't, what is going to be the difference between `Dictionary<string, object> CustomData` and `Dictionary <string, IBHoMFragment> Fragments`?

**Comment by IsakNaslundBh** [comment]
My two cents:

My spontaneous reaction to this would be that I would approve. 👍 

Have also been contemplating the two problems you raise here, and a dictionary could be the right way to solve this.

Before we implement though, think it would be good to think through and make sure that only having one of each fragment type will be true for all use cases. For the ones I can think of on the top of my head right now, I think this is true, but might be cases where it is not. After all, we have objects that have multiple properties of the same type (bars have two nodes for example), and maybe similar could be said for some fragment.

**Comment by IsakNaslundBh** [comment]
> In case we can't, what is going to be the difference between `Dictionary<string, object> CustomData` and `Dictionary <string, IBHoMFragment> Fragments`?

I read it as @alelom was proposing  `Dictionary<Type, IBHoMFragment> Fragments`, which is a bit of a difference and more restrictive, but makes it easier to work with in the code. Correct me if I am wrong

**Comment by epignatelli** [comment]
But wouldn't that be dangerous? 
We might have `Fragments[typeof(int)] = ""`? Or am I missing something?

**Comment by alelom** [comment]
> Before we implement though, think it would be good to think through and make sure that only having one of each fragment type will be true for all use cases. For the ones I can think of on the top of my head right now, I think this is true, but might be cases where it is not. After all, we have objects that have multiple properties of the same type (bars have two nodes for example), and maybe similar could be said for some fragment.

I thoroughly agree; and that is why I'm adding that I would also keep the CustomData as we have it, in addition to the Fragments. This is because it would give the maximum flexibility; that way however we should ask people to always implement a Fragment unless impossible, then use CustomData as a last resource.

**Comment by FraserGreenroyd** [comment]
I have no qualms in either case. There is a method in the Environment Engine which handles getting a specific fragment off an object [here](https://github.com/BHoM/BHoM_Engine/blob/master/Environment_Engine/Query/FindFragment.cs) but agree speed can be problematic.

However, I do agree with @epignatelli point about a certain level of danger in someone assigning the wrong fragment to a given type. But if you're going to put motorcycle tyres on a car, while it might go round and round you've got to expect some strange results. So it's whether we can trust/teach people not to do as @epignatelli has theorised.

Maximum flexibility is good @alelom but do we run the risk of confusing people with too many options?

**Comment by alelom** [comment]
> But wouldn't that be dangerous?
> We might have `Fragments[typeof(int)] = new MaterialFragment()`, or am I missing something?

Edu makes a fair point here as well. In other words, he's saying that
*the dictionary key could be of a type which is not correctly reflected in the dictionary value*.

He had a very good idea too, that **we might use an HashSet instead of a Dictionary**.

That might solve all problems: you should get the fast lookup without having to specify a redundant information (the type of the fragment in the Dictionary key).

**Comment by epignatelli** [comment]
I sneaked a change in the previous comment to explain what I meant :ninja:

**Comment by alelom** [comment]
>Maximum flexibility is good @alelom but do we run the risk of confusing people with too many options?

I get your point -- however I think that CustomData and Fragment actually *do different things*, and switching one for the other is not a 1:1 substitution. 

@al-fisher would be good to get your opinion as well 😄

**Comment by al-fisher** [comment]
> But wouldn't that be dangerous?

Yes - on the danger point. I am inclined to agree. Although with helper methods setting the correct Type in the dictionary obviously being possible for attaching fragment. (unless we go down protected/private route - we should really avoid) we can not stop big potential for user error!

> If the performance of fragments becomes a problem, would that be the sign that the property should be implemented as an actual class property, rather than a fragment?

No. The definition of a defining property can not be related to performance.


I do think we should investigate `HashSet<IBHoMFragment>`  as an option! Be good to get some thoughts on any disadvantages there. Presumably quick retrieval is being compensated by more computation at insertion. Assume this will not be a huge hit even for complex objects?

**Comment by epignatelli** [comment]
While searching around a little bit, it seems that `HashSet<>` could not a solution, since it does not provide a method for quick retrieval: https://stackoverflow.com/a/14651763/6655465 (??)
It is mainly used for operations between sets.

What we could do though, is to use a `KeyedCollection`, which would maintain the keys by its own and still [keep the performance up](https://stackoverflow.com/q/15904625/6655465).

```c#
    public class FragmentCollection<T> : KeyedCollection<Type, T> where T : BH.oM.Base.IBHoMFragment
    {
        protected override Type GetKeyForItem(T item)
        {
            return typeof(T);
        }
    }
```

**Comment by alelom** [comment]
I like Eduardo's solution. 

Just for the record, HashSet does provide a method for retrieval, but apparently [that's been added only on .NET 4.7.2](https://stackoverflow.com/a/50909955/3873799).

**Comment by al-fisher** [comment]
> Just for the record, HashSet does provide a method for retrieval, but apparently that's been added only on .NET 4.7.2.  

🤦‍♂🤦‍♀

**Comment by al-fisher** [comment]
I like the sound of the `KeyedCollection` 👍 
The added benefit (I shall indeed now call it a benefit!) of the whole proposed approach is the forcing uniqueness of the `Type` in the list of `Fragments`. I actually like this as a defining characteristic of a `Fragment` - that it must be unique on the object. Can be neat I think.

As for naming then I think we can have 
``` C#

namespace BH.oM.Base
{ 
    public class BHoMObject
    {
         public FragmentSet<IBHoMFragment> Fragments { get; set; } = new FragmentSet<IBHoMFragments>()
    }
}
```

**Comment by adecler** [comment]
I am globally happy with the proposal to go away from List for storing fragments. First, a few comments on what was said so far:

- Agreed on the fact that we can afford to only store one fragment of each type. This is [how Unity3D handles their components](https://docs.unity3d.com/ScriptReference/Component.GetComponent.html) so, if this is good enough for them, it should be good enough for us too.

- Agreed with @epignatelli that a dictionary would be awkward here and that KeyedCollection is a better match. 

- I am not 100% convinced that our definition of `FragmentSet` (© @al-fisher)  should be in the `BH.oM` namespace though. This is a technical object that is only there to complement C# so not really fitting the mould. Also not matching our compliance for BHoM objects. 

- If we are calling this `FragmentSet`, then we can define it as 
`FragmentSet : KeyedCollection<Type, IBHoMFragment>`.
No need to have to write `FragmentSet<IBHoMFragment>` all the time. (Plus, generic types are a pain)

Then, we should discuss performances and make sure our choice is the best for our typical user cases. Here's the result from a quick speed test on both adding and accessing elements from 3 types of collections: `Dictionary<Type, object>`, `KeyedCollection<Type, object>`, and `List<object>`. I have ran the test for various sizes of collection. This means
- for adding: adding on an empty collection until reaching that size
- for getting: getting elements from a collection of that size

Here's the results:

![image](https://user-images.githubusercontent.com/16853390/63142975-c4834580-c01e-11e9-9357-87e7e29f6976.png)

![image](https://user-images.githubusercontent.com/16853390/63142993-d1079e00-c01e-11e9-83f8-2e3590949ba3.png)

- It is fair to assume that the colections of fragments are generally going to be pretty small (<5, maybe <10 in some case). I have tested for larger collections while I was at it though but focus on the left half of the charts.
- As expected List is way faster to add but slower to access. It is a fair assumption that we will have more access operations than setters so going away from List makes sense.
- It is not surprising that KeyedCollections are slower than Dictionaries since they also maintain the ordered list. I didn't expect the difference to be so big on small collections though. Some food for thoughts in the way we want to implement `FragmentSet`.

**Comment by alelom** [comment]
That's awesome @adecler. I didn't expect KeyedCollection to be that slower in Adding either. I also agree with all of your statements -- however I'd still go for KeyedCollection as I can't see an alternative ATM. I'll do some more research but I'd keep that as my favourite choice for now.
