### ISSUE TITLE
Structure_oM: Add generic material and Section

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#564]
At the moment we have only specific material types, such as Aluminium, Concrete, Steel, Timber etc. I am wondering whether it would be good to have something generic, e.g. when working with materials that are not supported (soil, glass etc.) or when the material is unknown (e.g. on pull from other software).

Similar issue refers to SectionProperties: currently we need to be specific whether the section is concrete, steel, composite etc. Having a generic section would also be welcome, at least from the interop perspective.

What do you think @al-fisher @rwemay @IsakNaslundBh @JosefTaylor ?

**Comment by rwemay** [comment]
I _think_ this sounds good - can't think of a good reason why not, and as you say, is almost required to facilitate us supporting any material not yet centrally defined.

**Comment by IsakNaslundBh** [comment]
Happy to add this in. Have only had one argument against, and that is that it _could_ lead to a situation where toolkit devs feels it is easier to just give a generic material and generic section back rather than a Steel/Concrete etc, which _could_ be problematic further down the line. But this is something we can catch in PRs etc, so no real reason holding back adding this in to get more functionality.

**Comment by rwemay** [comment]
Great! I agree with the concern raised however, think that the right place to check that is in the respective pull request etc. itself. The issue isn't isolated to materials - bespoke/free-form cross section generation rather than from a database/specific cross-section for example.

**Comment by pawelbaran** [comment]
Thanks @IsakNaslundBh - could please ping me once this one is resolved? Revit_Toolkit will follow.
