### ISSUE TITLE
Structure_oM : Structure.MaterialFragments need to implement IBHoMFragment

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#588]
`Structure.MaterialFragments` are not currently  `IBHoMFragments` and thus can not be stored in a `FragmentList`

![image](https://user-images.githubusercontent.com/15924573/67112808-ff952700-f1cf-11e9-8878-cd3029645f25.png)

Suggested implementation of `IBHoMFragment` at the correct level in the chain of interfaces for Structural Material objects (Steel, Concrete etc.) 
e.g.
``` C#
 public interface IMaterialFragment : IMaterialProperties , IBHoMFragment
```
or potentially at `Physical` namespace level?

@IsakNaslundBh @FraserGreenroyd @alelom FYI

#### Test file(s):

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%2FBHoM%5Fissue588%2DMaterialFragment

**Comment by alelom** [comment]
Agreed, this should work straight away. 

I generally think the rule for compliance should be:

> **if it's named "`...somethingFragment`", it should implement `: IBHoMFragment`**

for this reason, I think the implementation is more appropriate at the level of the `IMaterialFragment` than at the `Phisical` namespace level (unless we want to rename `IMaterialProperties` as `IMaterialPropertiesFragment`).

**Comment by IsakNaslundBh** [comment]
yes, agreed, this has been the intention all along. Was not implemented straight away due to fragments being a bit unsettled when this was first done. Intention all along has been to get rid of the Material-properties from the physical material class and make structural Materials into IBHoMFragments.

**Comment by al-fisher** [comment]
OK perfect. Yes - makes sense. Thanks @IsakNaslundBh

**Comment by FraserGreenroyd** [comment]
I wonder if this is best done at the `Physical` level because the Environment material fragments also do not currently implement the `IBHoMFragment` interface as yet - they implement `IMaterialProperties` same as Structures, so do wonder if the best approach is within the `Physical` and enforce all future material fragments (regardless of discipline) to thus be `IBHoMFragment` or whether to leave it to individual disciplines to decide?

**Comment by al-fisher** [comment]
Ah - right

> and enforce all future material fragments (regardless of discipline) to thus be IBHoMFragment

This does get my vote. Assuming the plan has always been to remove `IMaterialProperties` and replace by a Physical Fragment.

@IsakNaslundBh - any objections?

**Comment by IsakNaslundBh** [comment]
No objections. I mean, it needs to get done on all levels, discipline level as well as physical if we remove the `IMaterialProperties` interface, agreed.

**Comment by IsakNaslundBh** [comment]
Bumping to 3.1 as need to be done with some care and coordination across disciplines and toolkits working with physical materials. @al-fisher @FraserGreenroyd @pawelbaran
