### ISSUE TITLE
Geometry_oM: Add TaperedProfile

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM#597]
#### Description:

A number of BHoM support software uses tapered sections and I don't think it would be too hard to implement.

A `TaperedSteelSection` would own two `SteelSection` objects, i.e. `SteelSectionStart` and `SteelSectionEnd` (or we could go the i/j naming convention). 

The constructor would take a `Fabrication`, `PlateRestraint `and `Material `input and override those stored in the `SteelSection `objects. This is to prevent having a `SteelSectionStart `with a different Material to the `SteelSectionEnd`. 

We could write an Engine method to produce average `SectionProperties `for the `SectionProfile`, so that a `TaperedSteelSection `can be used with Toolkits that do not support tapering - this would required a warning message.

@IsakNaslundBh @rwemay @JosefTaylor @alelom thoughts?

**Comment by JosefTaylor** [comment]
Very excited about this- all the cool projects are using tapered sections! I think if `SteelSectionStart` and `SteelSectionEnd` are profiles rather than sections, we get around the material issue. I also think this should be as general as possible- we'll certainly come across tapered concrete sections as well as tapered wood sections.

**Comment by rwemay** [comment]
Agree with @JosefTaylor on the excitment level and generalisation - should be inclusive of any section/material. I _almost_ suggested a list of steel sections so we could define a bar with any number of segments, but I think that's a bit too mad - and have not seen the use-case in any applications to date. I feel like it's where one of the recent research projects was hoping to go, but I think if more than start/end should be split into bars.

**Comment by JosefTaylor** [comment]
As a matter of fact, SAP2000 has tapered sections with a list of sections and stations. I think we could build our object as a list, but then just make a constructor which only takes a start and an end for now.

**Comment by JosefTaylor** [comment]
Could we have a `dictionary` of `stations as double` and `profile`?

**Comment by rwemay** [comment]
Boom! Glad I mentioned it in that case, I think it makes sense and adds flexibility. As you say the Engine methods can 'dumb down' the complexity/flexibility by using start/end etc. @IsakNaslundBh what do you think?! Also btw, loving that this is a 'simple problem to solve.' I'm quite sure it would not have been if we hadn't structured things the way we have - atomising and organising the oM.

**Comment by peterjamesnugent** [comment]
Agree on the generalisation and use of SectionProfile, I was just trying to mirror the current SteelSection, ConcreteSection etc. 

There should probably be an engine method that interpolates sections across Bar elements. So you feed in a list of ordered bars and the tapered sections, and it will interpolate the tapered section to get a smooth transition between the three.

An example of when this would be used is cross members beneath a deck, where the cross member has additional nodes to match the deck mesh and is subsequently broken in to several elements and only the start and end section are known.

**Comment by IsakNaslundBh** [comment]
Think this all make sense.

Agree with @JosefTaylor that this should be solved on the `Profile` level rather than the `Section` level, but to list out and summarise the options I think we have and that have been mentioned (which all should be able to handle either just start and end section or a `Dictionary<>`):

1. Add new `TaperedSteelSection` class that carries two/a list of `SteelSection`
1. Add a new `TaperedSteelSection` class that carries two/a list of `IProfile`
1. Add a new `TaperedProfile` class that carries two/a list of `IProfile`

I personally think option 3. would be the best way forward. Means we solve Steel/Concrete/soon to be added Timber+Aluminium in one go without the need for multiple new classes.

Then in terms of implementation, I think the dictionary approach could work quite well as

```
public class TaperedProfile : IProfile, IImutable
{
     public ReadOnlyDictionary<double, IProfile> Profiles {get;set;}
}

```
where the double corresponds to normalised length along the bar and hence needs to be between 0 and 1 (which is something we can/need to check in our create methods). And ofc as mentioned by @JosefTaylor , can have a create method that just takes start and end and sorts out the dictionary for us as well as query methods to get start and end profile.

Some things to figure out in terms of things like all the section constants, integration methods etc that to some extent become nonsensical but can make sure to just return 0 for them for a tapered profile until we have something more appropriate figured out.

**Comment by rwemay** [comment]
Perfect!

**Comment by IsakNaslundBh** [comment]
> There should probably be an engine method that interpolates sections across Bar elements. So you feed in a list of ordered bars and the tapered sections, and it will interpolate the tapered section to get a smooth transition between the three.

This is a good point. Need to be a lot more careful when performing operations such as splitting/snapping etc once we have something like this added!
