### ISSUE TITLE
Physical_oM: Add IElementXD to physical objects

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM#605]
#### Description:

To facilitate engine methods such as translate (SetGeometry methods need to be added).

**Comment by pawelbaran** [comment]
@al-fisher @IsakNaslundBh @FraserGreenroyd adding you since I believe you had a valid reason not to implement `IElements` to the elements from `BH.oM.Physical`.

Personally I believe this should be 100% fine for `IFramingElements`, but could be a bit problematic for `ISurfaces` since they can be nonplanar:
1. We would end up in having IElement2d implemented by a class that can represent an element of higher dimension. Having said that, see point 2.
2. Implementation should be relatively straightforward: we would need an extra check if the `Location` of an `ISurface` is `PlanarSurface` when calling `Geometry()` method on it.

What do you guys think?

**Comment by al-fisher** [comment]
Following @pawelbaran comment - adding to this milestone.

**Comment by al-fisher** [comment]
On 1 & 2 above - I think your 2 covers it. For now we can happily have explicit `IsPlanarSurface` check and return `NotImplemented` if not.
