### ISSUE TITLE
Data_oM: Add confidence to source

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM#612]
Following conversations with @rolyhudson  and @al-fisher , wondering if we should add a `Confidence` property (as a `double`) to the `Source` object. Thoughts @IsakNaslundBh

**Comment by rolyhudson** [comment]
I think it would be really helpful, should we define it as limited to a range of 0-1?

**Comment by al-fisher** [comment]
Sounds good.
I think we should limit as 0..1. As discussed a bit on this - any weighting in the BHoM - I think we should enforce normalising to -1.0..+1.0. Similar to standardising around SI for units. Normalised weights will simplify aggregation downstream.

We shall probably also require some clear documentation to help standardise a scale for `Confidence` 
i.e. What does my `0.8` mean in reference to your `0.7` say. Tricky! 😄

**Comment by IsakNaslundBh** [comment]
Kind of like the idea in general but one question I would raise though is if not all, at least central,  Datasets fundamentally should be a 1 in confidence.

As in, should we ever create and distribute a Dataset with Confidence rating of 0.1? If so, we need to make that extremely clear in the UI so that people don't start using it believing that this has been checked properly etc.

Also following @al-fisher s comment if we decide to add this in, maybe a Confidece enum or similar could be better with say 5 clear levels. Would then also automatically enforce a range and we could put some descriptive text around what each level mean.

**Comment by rwemay** [comment]
Yes great idea @IsakNaslundBh . This has come from an internal project using data from various sources for analytics. Its use is for predictions and metrics and some data points have more reliable sources than others. Importantly, a formal property lets us be transparent about that. Could be that there is a specific requirement on some dataset types (steel blue book) that require level 5.

**Comment by IsakNaslundBh** [comment]
@rwemay Yes, ok, that makes sense. As long as it is used for things like that I would agree!

My only reason for some caution with adding it is to not open a door for people not to vet/check the data properly before adding it in as it is easier to just drop the confidence than to check it! But as you say, we can put up some general guidelines for this and deal with it on a case by case basis.
As long as level 5 is the default and you need a good argument if you can not reach that, I think it generally should be fine. (Again, this is mainly talking about the Datasets in BHoM_Datasets)

**Comment by rwemay** [comment]
We could come up with a different class/interface that covers things that have to be 100% I guess. Alternatively could use the confidence property as another reinforcement of the principles.
