### ISSUE TITLE
Rename IObject as IBHoM

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#646]
This suggestion was originally raised in another thread here: https://github.com/BHoM/BHoM_Adapter/issues/131#issuecomment-533249032
Giving it its own issue to close out.

Conscious as always of avoiding Smurf code but it think in this case - renaming to introduce symmetry with IBHoMObject and IBHoMFragment I think will actually really add clarity. 
Indicating that classes that implement this interface are in the BHoM ecosystem.

**Comment by FraserGreenroyd** [comment]
I would support a move for the adding clarity that `IBHoMObject` is part of the BHoM and not independent (which `IObject` does, to an outsider, suggest - especially because we don't yet have an publicly available API which shows how `IObject` sits within our framework).

I would be happy to see a move from `IObject` to `IBHoMObject` but would need us to draw up a careful plan to trickle that update through, I'm not convinced we have the capacity for such a major change in 3.1 with our current workload for this milestone?

That said, 3.1 is the perfect milestone to do it while we're consolidating our existing work... so I'm torn and am re-convincing myself that 3.1 could work. I think I'll wait to see what the others think, if they're up for it than I'm sure we can make a plan to make it work in 3.1 if they agree with your thoughts @al-fisher as I do.

**Comment by al-fisher** [comment]
> I would be happy to see a move from IObject to IBHoMObject 

To clarify - I am only suggesting a simple rename of `IObject` to `IBHoM`.

Sorry @FraserGreenroy - was not sure if your comments above suggested something different

**Comment by FraserGreenroyd** [comment]
> > I would be happy to see a move from IObject to IBHoMObject
> 
> To clarify - I am only suggesting a simple rename of `IObject` to `IBHoM`.
> 
> Sorry @FraserGreenroy - was not sure if your comments above suggested something different

Sorry yes, `IBHoM` - early morning typing before a cup of tea has had me there! 🤦‍♂

**Comment by al-fisher** [comment]
Happy to get agreement on what the right course of action is - then we can schedule in appropriate milestone accordingly.

**Comment by alelom** [comment]
Completely agree on this. `IObject` is non descriptive.

**Comment by IsakNaslundBh** [comment]
Sorry, but not sure I fully agree on making this change.

Some things from previous conversations to keep in mind.

Firstly, think we need to not mix up two conversations here. From https://github.com/BHoM/BHoM_Adapter/issues/131#issuecomment-533249032 the discussion was about adding an interface to tag anything BHoM related. To me this sounds like an interface with no compliance regulations whatsoever, just something to tag a class as "BHoM". Could potentially see some use in this, but would see this as a new thing in this case.
Reason for saying this is from previous meetings regarding Compliance checks to be added by @FraserGreenroyd and @awakeman  for `IBHoMObjects` as well as `IObjects` where we stated what standard both of these needs to follow. The Adapters for example will not generally be able to comply to this, and I don't think we need to enforce them to do that. Hence, changing the name of `IObject` to `IBHoM` does not really resolve this.

I Personally prefer the having the "object" part of the name in the interface, at least the one discussed for the compliance. We have been relying on namespaces for a lot of other things to know that it is BHoM/a specific discipline etc, think we could do the same here.

All this being said, could be ok to add in a _new_ `IBHoM` interface to be used by literally everything, including adapters, if that is something we think could be useful.

**Comment by al-fisher** [comment]
Hmm ... yep, see your points above @IsakNaslundBh - but the direction I am coming from is  to remove ambiguity between C#'s native `System.Object` (which is nothing to do with BHoM) and our `IObject`. 

Totally agree with your comments on namespaces being key to removing ambiguity. We are exploiting that across all other namespaces with multiple `Panel` classes for instance.

Bu the ambiguity above with  `System.Object` is compounded when explaining the objects in the `BHoM.Base` namespace - `IObject` as it currently stands is named quite differently to all the other interfaces.

Options could be come up with a new name for `IObject` or alternatively rename the other interfaces `IBHoMFragement` and `IBHoMGroup` as `IFragment` and `IGroup` respectively - then leaving `IBHoMObject` as the special case.
That is an option too?

**Comment by IsakNaslundBh** [comment]
> Options could be come up with a new name for IObject or alternatively rename the other interfaces IBHoMFragement and IBHoMGroup as IFragment and IGroup respectively - then leaving IBHoMObject as the special case.
That is an option too?

Would personally prefer to go in this direction, if for nothing else than to avoid the smurf naming as mentioned by you before @al-fisher .

This is what we have done for other things as will, `IGeometry`, `IResult`, `IElementXD`, `IPanel` etc. For this case I could still see the use of an `IObject` as any of these (and that is what I personally always have looked at it as).

As a side note, I would probably keep the "BHoM" in the `IBHoMGroup` as that is an actual `IBHoMObject`, but fully agree with renaming `IBHoMFragement` to `IFragment`.

**Comment by IsakNaslundBh** [comment]
And as an extra note, I am fine with renaming `IObject` to `IBHoM` if everyone think that that is clearer, but wanted to highlight in my first comment that that does not solve the problem for the adapters !

**Comment by al-fisher** [comment]
No - does not solve the problem for the adapters - agreed. 
This why I pulled out as a separate issue. 

I could get behind renaming of `IBHoMFragment` to `IFragment` as it was in fact looking at this Interface and then the rest of the `Base` namespace that reprompted my raising of this issue as it stuck out as inconsistent.

**Comment by al-fisher** [comment]
To summarise ... following thread and discussion. 

#### Proposal is to rename `IBHoMFragment` to `IFragment`. 

See also comments on https://github.com/BHoM/BHoM_Adapter/issues/131#issuecomment-573792946

@adecler good to hear your thoughts? 
Then if makes sense and you're happy can update issue title/open new issue! 😄

**Comment by adecler** [comment]
I cannot agree more with @IsakNaslundBh. I was trying to formulate a reply when going through the thread and was very happy to realise than all I had to do was giving a thumb up to his comments :smile:.

To reinforce his point, `BH.oM.Base.BHoM` feels very weird to me and doesn't actually makes sense (since `IObject` is not a BHoM object), while `BH.oM.Base.IObject` is quite clear and mirrors the `System.Object` on purpose. 

Also really great catch on `IBHoMFragment` not being a BHoM object and therefore needing to be renamed `IFragment`. I think this is perfect to avoid confusion on when to use and when not to use `BHoM` in the class name.

**Comment by al-fisher** [comment]
Perfect! Thanks all. Will raise new issue for clarity
