### ISSUE TITLE
Common_oM : Remove BH.oM.Common.Interface.IObject2D

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#648]
#### Broken rules:
`BH.oM.Common.Interface.IObject2D` has been deprecated since 2.3 - Replaced by `BH.oM.Physical.Elements.ISurface` interface in Physical_oM

#### Suggestions to restore compliance:

Removal of deprecated class

@adecler @IsakNaslundBh @FraserGreenroyd FYI

**Comment by adecler** [comment]
A bit out of my depth here but, while I was trying to understand the difference between `IElement2D` and `ISurface`, I noticed that the remaining objects still interfacing `IObject2D` are
- Roof
- Wall
- Floor

`ISurface` objects are
- Extrusion
- Loft
- NurbSurface
- PlanarSurface
- Pipe
- PolySurface

`IElement2D` objects are
- Ceiling
- Opening
- Panel

Among all the `ISurface` and `IElement2D` classes, ceiling seems to be the closest to Roof, Wall, and Floor. 
So shouldn't we replace `IObject2D` with `IElement2D` instead of `ISurface` ?

On a side note, I couldn't find any engine method that would handle a ceiling, even if it is supposed to handle `IElement2D' (e.g. `IOutlineElements1D` covers Panels and Openings but not Ceilings.

**Comment by al-fisher** [comment]
Ah - the `Floor`, `Wall` and `Floor` objects implementing `IObject2D` were also deprecated in 2.3!
They are in the `BH.oM.Architecture.Elements` namespace (these objects were migrated to Physical)
I will raise issue to remove these two now in this milestone.

Thanks @adecler

**Comment by al-fisher** [comment]
To be scheduled based on outcome of Versioning workshop planned for end of milestone

**Comment by IsakNaslundBh** [comment]
Closing this as Common_oM was removed in https://github.com/BHoM/BHoM/pull/913.

@al-fisher feel free to re-open if you disagree.
