### ISSUE TITLE
Geometry_oM: Make PlanarSurface immutable

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#676]
#### Description:

Following the discussion in [#1429](https://github.com/BHoM/BHoM_Engine/pull/1429), `PlanarSurface` should be immutable and `Create` should check planarity of the input.

**Comment by kThorsager** [comment]
Should also ensure that it's a valid surface by checking if Internal curves are overlapping and are non self-intersecting

**Comment by kThorsager** [comment]
Will need action in:
BHoM; architecture_oM, Geometry_oM (does not clash with #855), Physical_oM
BHoM_Engine; Geometry_Engine
Revit
Rhinoceros_Toolkit

Think this mostly needs some coordination with @pawelbaran on when it's possible in Revit_Toolkit.

Then I'm concerned about the `null`of what used to be `new PlanarSurface`s in a lot of objects
![image](https://user-images.githubusercontent.com/53530468/81581412-9f054b80-93a6-11ea-9aa5-83b2bbc6eee4.png)
Which I'm both unsure of how to test and what to do about.
(maybe: `= new PlanarSurface(null, new List<ICurve>)`, but would still introduce problems for those who used it to set thing on)

And BHoM_UI gets an exception instead of sending the old constructor to Versioning

**Comment by kThorsager** [comment]
Will need action in:
BHoM; architecture_oM, Geometry_oM (does not clash with #855), Physical_oM
BHoM_Engine; Geometry_Engine
Revit
Rhinoceros_Toolkit

Think this mostly needs some coordination with @pawelbaran on when it's possible in Revit_Toolkit.
(Files modified: 
- C:\GitHub\Revit_Toolkit\Engine_Revit_UI\Convert\Geometry\FromRevit\Surface.cs
- C:\GitHub\Revit_Toolkit\Engine_Revit_UI\Query\PlanarSurfaceDictionary.cs

)

Then I'm concerned about the `null`of what used to be `new PlanarSurface`s in a lot of objects
![image](https://user-images.githubusercontent.com/53530468/81581412-9f054b80-93a6-11ea-9aa5-83b2bbc6eee4.png)
Which I'm both unsure of how to test and what to do about.
(maybe: `= new PlanarSurface(null, new List<ICurve>)`, but would still introduce problems for those who used it to set thing on)

And BHoM_UI gets an exception instead of sending the old constructor to Versioning, problematic.
Further testing makes it look like BHoM_UI handles the default constructors separately which keeps missing ones from being sent to versioning.

Known issue @adecler or should I raise one? (or perhaps intended)

**Comment by pawelbaran** [comment]
@kThorsager this should not conflict with the current works going on in Revit_Toolkit. `PlanarSurfaceDictionary` is meant to be refactored in this Milestone so would not be too desperate about keeping it clean and tidy. To sum up, I am fine with getting this ticked off any time.

**Comment by kThorsager** [comment]
Great, then I'm ready as soon as Versioning works or that can be said to be an acceptable loss

**Comment by IsakNaslundBh** [comment]
>Then I'm concerned about the `null`of what used to be `new PlanarSurface`s in a lot of objects
![image](https://user-images.githubusercontent.com/53530468/81581412-9f054b80-93a6-11ea-9aa5-83b2bbc6eee4.png)
Which I'm both unsure of how to test and what to do about.
(maybe: `= new PlanarSurface(null, new List<ICurve>)`, but would still introduce problems for those who used it to set thing on)

I would argue null is better here than an empty planar surface. Think quite a few cases are better off using nulls over empty objects, and for this case it is not even sure that you want to be using a planar surface.

Ofc the implications of this needs to be checked through though.

**Comment by adecler** [comment]
> I would argue null is better here than an empty planar surface. Think quite a few cases are better off using nulls over empty objects, and for this case it is not even sure that you want to be using a planar surface.

Agreed.

> And BHoM_UI gets an exception instead of sending the old constructor to Versioning, problematic.

I don't think constructor are supported for versioning at all. The idea is that they are not exposed in the UI anyway.

**Comment by kThorsager** [comment]
> > And BHoM_UI gets an exception instead of sending the old constructor to Versioning, problematic.
> 
> I don't think constructor are supported for versioning at all. The idea is that they are not ment to be exposed in the UI anyway.

I'm trying to make sure that the old default constructor, which is available in the UI, gets versioned into the `Create` method in the Engine, which has the same inputs.

**Comment by IsakNaslundBh** [comment]
> I don't think constructor are supported for versioning at all. The idea is that they are not ment to be exposed in the UI anyway.

Assume you mean the PropertyAsignment one @kThorsager

**Comment by kThorsager** [comment]
I want this to be the new one in the UI:
![image](https://user-images.githubusercontent.com/53530468/81783032-ad607e00-94f2-11ea-9bbd-f2a76aaa007a.png)

The property assignment one isn't exposed, (if I follow?)

**Comment by IsakNaslundBh** [comment]
It is not exposed for immutable objects, no. Was mostly commenting to try to clear the confusion between constructors and property assignment methods components! :)
