### ISSUE TITLE
LifeCycleAssessment_oM : Update EnvironmentalProductDeclaration properties to use units instead of strings 

### ISSUE THREAD

**Issue by enarhi** [BHoM/BHoM#745]
#### Description:
EnvironmentalProductDeclaration properties currently use strings with string parsing to handle conversions for evaluate methods. These properties will need to be updated to take advantage of general units handling methods instead of string parsing buried in LifeCycleAssessment_Toolkit.

**Comment by michaelhoehn** [comment]
I believe this has been refactored out since the OP, but please feel free to point out any specifics in the code if I'm missing something. The only strings in the current set up aren't being used in any eval methods now, but could be useful EPD specific properties. 

These objects will also be going through a significant refactor in the coming milestone to simplify the object class.
