### ISSUE TITLE
Physical_oM: Store IMaterialProperties on IMaterialProperties?

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM#764]
#### Description:
As #749 is making all `IMaterialProperties` into `IFragments` and as we're working towards allowing for more trans-disciplinary work, we could start storing `IMaterialProperties` on the `IMaterialProperties` when we create a `IMaterialProperties` from a Physical Material. 
Which would allow us to store a fuller `Material` definition on for example `Bars`. Especially those created from Revit which atm loose all that information once they are created from their `IFramingElements`.

Now, I'm not sure of the exact reason `Bar` can't store a Environmental material, but I'm assuming it's more about not using the wrong material with the wrong object (Bar might be a bad example as Environments does not have a 1d definition), but this would be more about not losing data, as for a user to assign one they would first still have to assign a Structural material, (and it would also be difficult to assign)

The one thing which would be 'weird' is that is would make the only difference between `Material` and `IMaterialProperties` that one has a 'master' `IMaterialProperties`.

Appropriate updates to engines would be necessary.

Still mostly a thought, (also not really a oM change as mush as a philosophy change on what we place where)

FYI @al-fisher

**Comment by kThorsager** [comment]
Closed due to ensuring scope of responsibility for disciplines

**Comment by al-fisher** [comment]
Yes - thanks @kThorsager. The discussion here was that the framework does not support explicit interdependencies between discipline code by design. Thus at a framework level we should not encourage storing cross-discipline data on another discipline’s objects. Responsibility will be ambiguous. 
e.g. A `Structural.Bar` cannot own an `Environment.Material` 

Multi-disciplinary data _CAN_ be stored on Physical objects (and similar) and naturally there are Transdisciplinary objects which might exist and be dependant on multiple disciple code/data. But not cross-discipline.
