### ISSUE TITLE
Environments_oM Question

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM#779]
After the descriptions exercise that we embarked on, we noticed quite a few opportunities for consolidation/clarification around our objects in Environments. We want as many Environments developers/end users to contribute to these questions as possible, so please add your own personal review/answers to the questions as a comment to this issue.

**CLIMATE:**
-Revise the Location object to the more agnostic Elements folder, it could be utilized by the Building object
-Revise the name "SpaceTime" to just Time

**ELEMENTS:**
-Revise the Building Type enum (currently only includes 3 types, similar to Space Types, should the type just be a string? how can we further utilize the concept of BuildingType?)
-Revise the Building Object (latitude and longitude could come from the Climate Location object
-Question: Should the building object contain all objects (openings, spaces) and go into the Document Builder?
-Add Zone object, currently referenced by the space object, but as a list and by the ConnectedSpaces concept on Panels
-Question: Panel Construction from Physical constructions, could this come from a local/environments definition for construction?
 
**EQUIPMENT:**
-Remove all Equipment objects, these belong in MEP

**FRAGMENTS:**
-Question: are these fragments only being utilized by the XML Toolkit? Should they move to the XML Toolkit?
-Revise AnalyticalConstruction properties (conflicting R/U values)

**GAINS:**
-Remove Emitter gain
-Remove Internal Condition
-Remove ViewCoefficient Property (redudant with RadiantFraction) from Lighting, Equipment, People, Plug
-Revise Profile properties (Colin)
-Revise Thermostat properties (should we have a space setpoint property that's associated with it?)
-Revise position of Ventilation (it's not a gain), also add property for Air Change Rate (add method for people/area and VRP with zones)
-Revisit context of the pollutant gain (give better examples in description)
-Revise Infiltration Gain properties (add property for construction tightness and a method with exterior crack area included)
-Revise Space Object's ability to take plug and/or equipment
-Add Occupancy object (and engine method with an input of people gains + occ)
-Add Humdistat (Denzil/Colin's suggestion)

**MATERIAL FRAGMENTS:**
-Question: are these fragments only being utilized by the XML Toolkit? Should they move to the XML Toolkit? Regardless Gas should not contain Roughness as a property

**RESULTS:**
-Question: How are these objects currently being utilized?

![image](https://user-images.githubusercontent.com/34316256/78596906-90150180-781a-11ea-889d-cfff5356a262.png)

![image](https://user-images.githubusercontent.com/34316256/78596923-960ae280-781a-11ea-998b-2b8c4be9f9d9.png)

**Comment by FraserGreenroyd** [comment]
Thanks @kayleighhoude - would second the call to action for a lot of us to provide feedback on the points you make. My tuppence worth is included below.

In addition, I would say it's good to remember some key things with regards to the Environment oM (as it the case with the BHoM in general), of being as agnostic as possible, and flexible with regards to potential workflows which may or may not be immediately apparent.

Definitely a good amount of feedback is important here to get a good consensus moving forwards. I would like to stipulate clearly that I am very open to different viewpoints on the below and would like to stress this are just my personal opinions!

> **CLIMATE:**
> -Revise the Location object to the more agnostic Elements folder, it could be utilized by the Building object
> -Revise the name "SpaceTime" to just Time

I would agree with moving the `Location` object to the `Elements` folder, it can be used by a host of objects, or it could become a fragment to be used on any object?

I think @tg359 originally coined the object as the `SpaceTime` object due to it containing both location data and time data (thus becoming a point in Space and Time). Would a `Time` object which also contained a `Location` attribute be intuitive?

> **ELEMENTS:**
> -Revise the Building Type enum (currently only includes 3 types, similar to Space Types, should the type just be a string? how can we further utilize the concept of BuildingType?)

From a development point of view I am against using `string` properties in too many places because we run the risk of becoming a `stringly-typed` set of objects. It may be best to build out the categories for the BuildingType instead?

> -Revise the Building Object (latitude and longitude could come from the Climate Location object

Agree.

> -Question: Should the building object contain all objects (openings, spaces) and go into the Document Builder?

I would be cautious here of the reference to `DocumentBuilder` which is an XML concept (and one which will be going away at some point soon).

In an early iteration of the Environment oM, the `Building` object did contain all of the elements of the building, but this gave us a massive object which had to be maintained as we moved through the workflows, which is why everything is more sort of split up in the way it is now. A single `Building` object is of course the default that most software developers would prefer, but a core BHoM philosophy has been about trying to help bring computation to the masses.

For this reason, I did opt to split the `Building` object up into its component parts and not have the `Building` own them. What this means for most workflows is that, if I want to change one panel in a model, I don't have to search the `Building` to find the `Space(s)` which contain the `Panel` and then update it. I can have a list of panels which make a building shell by their geometry, and just update one item in that list.

My personal feeling is, in line with BHoM philosophy, this shouldn't be done.

> -Add Zone object, currently referenced by the space object, but as a list and by the ConnectedSpaces concept on Panels

What would the Zone object contain? Just a list of `Spaces`, or would it also then include `Gain` data? (I'm unfamiliar with `Zone` besides as a grouping of spaces so may not be seeing the benefits here?)

> -Question: Panel Construction from Physical constructions, could this come from a local/environments definition for construction?

The way a construction is currently set up is as follows:
 - A construction is a physical, real world element (from Physical oM), that is made up of layers
 - Each layer is a physical, real world element that contains a material, and a given thickness
 - Each material is a physical, real world element that can make up something we could touch on a single layer of a construction
 - Each material contains, as fragments, analytical properties that define how that material reacts within each discipline. We have `EnvironmentMaterial` and structures have their own as well. The properties of these material fragments are then Environments specific, related to our workflows/data.

Thus (at the moment), a Panel contains a physical construction which in turn will contain the analytical properties it needs for analysis. This was originally done when structures and environments aligned last year, as we did have our own construction object, but structures needed one too and we didn't wish to duplicate too much code/definitions for core objects (hence, Physical oM was born).

We could perhaps look at having an analytical representation of a construction again, and query it from a physical construction?

> **EQUIPMENT:**
> -Remove all Equipment objects, these belong in MEP

Seems a little greedy :wink: but I can agree with it

> **FRAGMENTS:**
> -Question: are these fragments only being utilized by the XML Toolkit? Should they move to the XML Toolkit?
> -Revise AnalyticalConstruction properties (conflicting R/U values)

The fragments are utilised in a number of toolkits, including XML, Revit, TAS, and EnergyPlus to name but a few. The fragments are agnostic (as best as can be, could still be improved further I'm sure) but not specific to gbXML for the XML toolkit, so would not support moving them there.

Analytical Construction fragment was made in response to the discussion in #615 - but happy for the object to be revised, what would the revision look like?

> **GAINS:**
> -Remove Emitter gain
> -Remove Internal Condition
> -Remove ViewCoefficient Property (redudant with RadiantFraction) from Lighting, Equipment, People, Plug
> -Revise Profile properties (Colin)
> -Revise Thermostat properties (should we have a space setpoint property that's associated with it?)
> -Revise position of Ventilation (it's not a gain), also add property for Air Change Rate (add method for people/area and VRP with zones)
> -Revisit context of the pollutant gain (give better examples in description)
> -Revise Infiltration Gain properties (add property for construction tightness and a method with exterior crack area included)
> -Revise Space Object's ability to take plug and/or equipment
> -Add Occupancy object (and engine method with an input of people gains + occ)
> -Add Humdistat (Denzil/Colin's suggestion)

Would we replace `Emitter` and `IC` or move them to MEP or is this a removal completely? Is their data/function captured by other objects? (This is my lack of engineering knowledge now so eager to learn and understand where these ought to come from :smile: ). @tg359 I think your thoughts on this particular bit would be welcome as this seems to be linked closely with the energy stuff which you have more knowledge of than I? :smile:

> **MATERIAL FRAGMENTS:**
> -Question: are these fragments only being utilized by the XML Toolkit? Should they move to the XML Toolkit? Regardless Gas should not contain Roughness as a property

See previous answer regarding fragments and their utilisation.

As for `Gas` having a roughness, this is because the interface object states all Environment Materials should define a roughness property, so this forms a sort of contract that our classes have to adhere to. The interface properties were selected as the ones used mostly by pretty much all analysis packages when working with materials, and a desire to not have to check if the `typeof(IEnvironmentalMaterial)` became a Gas or a Solid, but to trust the property would exist.

I do agree though that roughness of a gas could be confusing, but this would need careful mapping out if we were to change it. Other thoughts would be good on this one.

> **RESULTS:**
> -Question: How are these objects currently being utilized?

Currently they're not, they need to be expanded on though - so thoughts very much welcome on that too :smile:

Tagging some other people for input as well:

@MajaLindroth @jakewilliams881 @ajensen19 @JAbboudBH

**Comment by BingWangUS** [comment]
> Thanks @kayleighhoude - would second the call to action for a lot of us to provide feedback on the points you make. My tuppence worth is included below.
> 
> In addition, I would say it's good to remember some key things with regards to the Environment oM (as it the case with the BHoM in general), of being as agnostic as possible, and flexible with regards to potential workflows which may or may not be immediately apparent.
> 
> Definitely a good amount of feedback is important here to get a good consensus moving forwards. I would like to stipulate clearly that I am very open to different viewpoints on the below and would like to stress this are just my personal opinions!
> 
> > **CLIMATE:**
> > -Revise the Location object to the more agnostic Elements folder, it could be utilized by the Building object
> > -Revise the name "SpaceTime" to just Time
> 
> I would agree with moving the `Location` object to the `Elements` folder, it can be used by a host of objects, or it could become a fragment to be used on any object?
> 
> I think @tg359 originally coined the object as the `SpaceTime` object due to it containing both location data and time data (thus becoming a point in Space and Time). Would a `Time` object which also contained a `Location` attribute be intuitive?
> 

For location, I think this is used to define weather data condition, in case we don't have a Building object. It make sense to me to keep the climate location, and assign it to a Building object when needed. Or let the Building object refer the Climate Location when needed. Keeping only one does not make too much a difference.

For SpaceTime, I agree on splitting it into space(location) and time. Time will be changing but location never changed. It may waste to create a list of Time object with the same location. Also, do we need a Time object as the system already have a DateTime object? Will it help to make the code faster? System DateTime object may give us more functions built in.

**Comment by rboulton-BH** [comment]
Comments following discussion with @FraserGreenroyd, @vbeardow, @RasmusCanfjorden & @MajaLindroth:

> ELEMENTS:
Revise the Building Type enum (currently only includes 3 types, similar to Space Types, should the type just be a string? how can we further utilize the concept of BuildingType?)

>From a development point of view I am against using string properties in too many places because we run the risk of becoming a stringly-typed set of objects. It may be best to build out the categories for the BuildingType instead?

Generally in support of further populating the list of BuildingType enums. These can and should probably reference building types in guidance e.g. CIBSE/ASHAE. If appropriate, these should also be coordinated with related data sets e.g. internal gains of typical building type

Investigation required into how building orientation is currently handled? Is this dealt with within software toolkits? Does this need to be a new object? Is it just not necessary?

Need some more clarity on what a 'Zone' means to MEP as it is typically not used in analysis. Currently it is assumed that a Zone is just a collection of Spaces. Also need to know how they will be used. Perhaps it should sit within MEP_oM?

Happy for Ventilation to be a separate folder from Gains. Should include infiltration, natural ventilation (e.g. opening windows) and mechanical ventilation. Review in line with related developments in MEP_oM

Occupancy & people gain inherently linked rather than separate objects. Perhaps occupancy density to be included as a property of People gain. Also include metabolic rate?

**Comment by FraserGreenroyd** [comment]
I have now prepared the issues from this question issue into separate issues for this sprint and will get them closed out ASAP. I am closing this issue as completed in its purpose of fuelling discussion on these points.
