### ISSUE TITLE
Is it OK to allow properties and CustomData keys with same name?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#815]
#### Description:

Currently it is possible to have a `CustomData` key that has the same name as one of the properties. This becomes an issue in Revit_Toolkit when all parameters of pulled element get copied over to the resultant BHoM object leading to e.g. `Level` having both property and `CustomData` key named _Elevation_: https://github.com/BHoM/Revit_Toolkit/issues/578

Besides it being confusing, it is particularly dangerous once `SetProperty` is used.

I can block it inside Revit_Toolkit, but shouldn't it be disallowed on framework level?

**Comment by adecler** [comment]
@pawelbaran , Can you clarify how this happens ? 

Looking at the SetPropertyValue method, a property will be assigned to CustomData **only if** there is no existing property with name. So the only thing that comes to in mind for the UI side is if the user assign a new dictionary directly to CustomData (we could add protection around that to warn the user if matching properties are found in the dictionary).

Otherwise, if it happens from C# code, then it something that needs to be picked up during the PR review process.

**Comment by pawelbaran** [comment]
Right, on `SetPropertyValue` a property will be assigned to `CustomData` only if there is no existing property with given name - that is fine.

The problem lies in the fact that the object _can_ have a property and `CustomData` key with same name. As mentioned in initial description:
> This becomes an issue in Revit_Toolkit when all parameters of pulled element get copied over to the resultant BHoM object leading to e.g. Level having both property and CustomData key named _Elevation_

Imagine that then the `Elevation` property is set with `SetProperty`, leading to the case where a single `Level` object has two conflicting sources of information about its elevation. That is what I would like to eliminate - could possibly be good to do it on framework level as this problem may reappear in other realms that Revit_Toolkit too.

**Comment by pawelbaran** [comment]
@rwemay blocking it on UI/SetProperty level will not help once the `CustomData` key and property are already created - the conflicting information is already there.

I would rather disallow setting non-unique `CustomData` keys at all - this would, however, require implementing additional mechanics to `BHoMObject` and possibly implementation a custom collection for `CustomData`. This does not perfect either. Thoughts?

**Comment by alelom** [comment]
While I get your worry about CustomData storing a key named like an existing property, I am still unclear as per how this happens in your case.

You say that:
> Besides it being confusing, it is particularly dangerous once SetProperty is used.

but, given that `SetProperty` actually first checks if a property exists, and only if that fails then proceeds to store the value in CustomData, I can't see how the use of Setproperty can be deemed dangerous for data redundancy.

I think I am still missing how the duplication happens in your data. To my understanding, it can't be a fault of SetProperty.

**Comment by pawelbaran** [comment]
Duplication procedure:
1. Pull Revit level
2. Revit level converted to BHoM `Level` with `Elevation` property
3. Post-convert action copies all Revit parameters to BHoM object's `CustomData`, including Revit element's _Elevation_ parameter

Then if you want to update elevation and push/update, confusion starts:
1. `SetProperty` changes property, but `CustomData` stays the same
2. On push Revit element will be updated based on BHoM object, then its parameters are overwritten by `CustomData`

**Comment by al-fisher** [comment]
I think the solution to this might be that we now start formalising where we copy all the Revit parameters. Storing as a fragment - rather than simply in CustomData?
@rwemay relates to our chat this morning on formalising our common approach to parameters in the BHoM.

We have previously discussed limiting the use of CustomData to only volatile date directly from the user - so I think formalising a `RevitParameters` Fragment might help - greater protection can be provided at creation

**Comment by pawelbaran** [comment]
@al-fisher this will not resolve the issue of information being doubled in object property and `RevitParameters` fragment.

**Comment by alelom** [comment]
> 3. Post-convert action copies all Revit parameters to BHoM object's `CustomData`, including Revit element's _Elevation_ parameter

this seems to be the problem then. We need to rise an issue in Revit about this.

This "post-convert action" should either:
a. use `SetProperty` in order to store the Revit parameters on the object, OR
b. a function that does the same thing as SetProperty (check if there is a property named like that and update that property, only if that fails then fallback on store in CustomData).

I'd avoid (b) to reduce code duplication. 

The problem with (a) is that `SetProperty`'s whole code is in the UI, if I'm not mistaken.  
@adecler I already had another case were I wanted to use this "SetProperty" code elsewhere. Maybe worth moving most of its logic up in the Reflection engine?

**Comment by alelom** [comment]
> Tend to agree that this would be good to block at the framework level, although not sure we'll be able to catch all cases without a pretty major change? We can block on the UI side with SetProperty.

I would tend to disagree with this. I think that we should keep CustomData free of such a restraint, and rather be careful on how we set the properties of the object. This would be against the implicit "freedom" of CustomData. Every time you add to the `Dictionary<string, object>` you'd have to know that a check is needed over the entire collection of the host object properties, or else the add might just fail. Not something I'd expect out of a simple collection type.

**Comment by pawelbaran** [comment]
`SetProperty` would not be 100% solution in my case @alelom: after setting a value to property in points 1. and 2. of the workflow above:

> 3. Post-convert action copies all Revit parameters to BHoM object's CustomData, including Revit element's Elevation parameter 

Point 3. would overwrite the property again. So actually what I am aiming for is:

```
if (property does not exist)
{
    copy parameter to customData;
}
else
{
    do nothing;
}
```

Is that something we would like to have on framework level? It could be a standard method in BHoM_Engine.

**Comment by alelom** [comment]
I still can't see how `SetProperty` would not solve it 100%, as the only difference is that the `else` part would be "set the property again" instead of "do nothing" but the end result would be the same. If for any reason you _must_ avoid setting again the same value, it's not hard to add a check for the value ("is the value you want to set equal to the value the property already has? If so do nothing").

Also, the `if (property does not exist)` requires a recursive check on the object properties that is already taken care of in `SetProperty`; you would have to duplicate that logic in whatever function you plan to implement.

**Comment by pawelbaran** [comment]
We have a BHoM object that has, `Material` property that is another BHoM object. At the same time, Revit element has a Material parameter that is, say, a string - the code would try to set the property running into issues - will it crash or set to null or what? And what if types would match but values not? Etc. etc.

**Comment by alelom** [comment]
Understood now. 
So you'd need the "recursive search" for the Property only. 

Also, I might be wrong on where the code for that part is. If everything you need is in the Reflection_Engine, you can already plough on and simply implement [the logic you stated above](https://github.com/BHoM/BHoM/issues/815#issuecomment-617826182).

Let's hear others' opinions.

**Comment by rwemay** [comment]
This sounds more like a conflicting properties issue than unique naming(?) And I think potentially does relate to the issue raised this morning here #824 . It won't solve it on it's own, but the idea is to formalise things _like_ Revit parameters, and formalise the concept of conflicts/updates between these and formal object properties. Essentially looking for a slightly more formal/robust approach to deal with SharedParameters in a global/BHoM sense, inclusive of parameter mapping. I feel like I'm confusing the issue rather than helping - needs a call!

**Comment by pawelbaran** [comment]
I like the concept @rwemay. However, to confuse a bit more, on Push the `CustomData` is mapped back to Revit parameters. So even if we move Revit parameters to a fragment. updating property will not resolve the problem - the fragment will still try to overwrite the parameter back on push.

The way in which Revit parameters are mapped against BHoM object's properties is really tricky:
- on pull, Revit parameters determine properties of a BHoM object on convert, then all of them get copied over to `CustomData`
- on push, BHoM object's properties determine some parameters of Revit element, later `CustomData` gets copied over to parameters (effectively overwriting the changes made by BHoM object's parameters)

Once you put on top of that the fact that Revit element's geometry is driven not only by its location, but also by its parameters (e.g. offsets) you get a solid puzzle.

**Comment by rwemay** [comment]
Yeah, didn't think it was going to be a simple one! Let's get a workshop set up. Hopefully not too urgent - can it be after next week?

**Comment by adecler** [comment]
- Agreed with @alelom (except for `SetPropertyValue` that is in the reflection engine, not in the UI). `SetPropertyValue` already provides the necessary checks, I wouldn't add more constrains on CustomData than that.
- To me, looks like this is something to take care of in the Revit toolkit (although I am still unclear on what is really going on that @pawel is considering not a Revit specific problem)
- Agreed with @rwemay , a workshop would probably be good

**Comment by pawelbaran** [comment]
Let's give it a shot in tomorrow's standup to see if we can cover it in 10 mins, and if not then let's set up a workshop - how does that sound?

**Comment by pawelbaran** [comment]
As discussed and agreed, creation of `CustomData` keys equal to property names should be disallowed on adapter level. Closing this as resolved, thanks!
