### ISSUE TITLE
LifeCycleAssessment_oM: Error related to serialization of the LifeCycleAssessmentResult object

### ISSUE THREAD

**Issue by enarhi** [BHoM/BHoM#928]
#### Description:
As below:
![image](https://user-images.githubusercontent.com/6752345/85079729-63675980-b17c-11ea-821d-1b0bd95ebe43.png)

#### Steps to reproduce:
Attempt to serialize a LifeCycleAssessmentResult object.

#### Expected behaviour:
Proper serialization.

#### Test file(s):
Any file with a LifeCycleAssessmentResult object, which is then pushed toMongo or fed into  ToJson component.

**Comment by FraserGreenroyd** [comment]
@enarhi I cannot replicate this. There have been updates to Serialiser Engine and the LifeCycleAssessment Result object to assist with Serialisation.

Are you using the latest `master` branch for BHoM and BHoM_Engine, OR (more ideally), running a recent daily alpha?

See image below for successful serialisation following this mornings PR to the LCA oM.

If you're still getting the issue, I advise internalising your data and uploading to this issue, because following the instructions in your 'test files' section does not reproduce the error for me.

![image](https://user-images.githubusercontent.com/18049174/85080984-96ccd700-b1c2-11ea-8ded-ece0366022b7.png)

**Comment by adecler** [comment]
What a timing! I now fix issues before they are raised 😋 
@enarhi , see https://github.com/BHoM/BHoM/pull/926
This is now be part of the daily alphas as well.

**Comment by enarhi** [comment]
@adecler haha, brilliant! Just grabbed the 0619 alpha and it is working beautifully now. Thanks to you and @FraserGreenroyd for the quick response.
